### ISSUE TITLE
Extension is noisy about missing 'prettier' module when package.json can't be parsed

### ISSUE THREAD

**Issue by roblourens** [prettier/prettier-vscode#1198]
- Open a project that does not use prettier
- Change package.json to not be valid json, e.g. insert some random text
- Open a markdown file
- Get annoying notification every time a markdown file is opened:

![image](https://user-images.githubusercontent.com/323878/72363143-308ad800-36a9-11ea-95da-4e18943d99e4.png)

```
["INFO" - 12:09:25 AM] Extension Name: "prettier-vscode".
["INFO" - 12:09:25 AM] Extension Version: "3.18.0".
["ERROR" - 12:09:25 AM] Failed to load prettier from ''
Unexpected token d in JSON at position 3483 while parsing near '... "gulp package"  },dsf  "contributes":...' 

   98 |     "major": "npm version major -m '%s'",
   99 |     "package": "gulp package"
> 100 |   },dsf
      |     ^
  101 |   "contributes": {
  102 |     "breakpoints": [
  103 |       {

JSONError: Unexpected token d in JSON at position 3483 while parsing near '... "gulp package"  },dsf  "contributes":...' 

   98 |     "major": "npm version major -m '%s'",
   99 |     "package": "gulp package"
> 100 |   },dsf
      |     ^
  101 |   "contributes": {
  102 |     "breakpoints": [
  103 |       {

	at e.exports (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253571)
	at AsyncFunction.e.exports.sync (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253103)
	at AsyncFunction.e.exports.sync (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:249917)
	at t.ModuleResolver.findPkg (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:246650)
	at t.ModuleResolver.findPkg [as findPkgMem] (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:247210)
	at t.ModuleResolver.requireLocalPkg (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:245330)
	at t.ModuleResolver.getPrettierInstance (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:243969)
	at t.LanguageResolver.getSupportLanguages (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242420)
	at t.LanguageResolver.allEnabledLanguages (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242028)
	at t.default.selectors (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:347789)
	at t.default.registerFormatter (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:347056)
	at t.activate (/Users/roblou/.vscode-insiders/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:86609)
	at Function._callActivateOptional (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:697:141)
	at Function._callActivate (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:696:810)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:960
	at async Promise.all (index 12)
["INFO" - 12:09:25 AM] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 12:09:25 AM] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["ERROR" - 8:35:05 AM] Failed to load prettier from ''
Unexpected token d in JSON at position 3483 while parsing near '... "gulp package"  },dsf  "contributes":...' 

   98 |     "major": "npm version major -m '%s'",
   99 |     "package": "gulp package"
> 100 |   },dsf
      |     ^
  101 |   "contributes": {
  102 |     "breakpoints": [
  103 |       {

JSONError: Unexpected token d in JSON at position 3483 while parsing near '... "gulp package"  },dsf  "contributes":...' 

   98 |     "major": "npm version major -m '%s'",
   99 |     "package": "gulp package"
> 100 |   },dsf
      |     ^
  101 |   "contributes": {
  102 |     "breakpoints": [
  103 |       {
```

- This was annoying since I am not even using Prettier in this project. Mabye it could wait to show an error until I tried to invoke Prettier?

**Comment by Stanzilla** [comment]
This fork does it a bit better, might be worth looking into https://github.com/SimonSiefke/prettier-vscode

**Comment by ntotten** [comment]
I think you will want to set the `requireConfig` option. There is a bug right now though that will be fixed soon. See: #1161
