### ISSUE TITLE
Add an option to disable loading prettier module if referenced in package.json as a dependency

### ISSUE THREAD

**Issue by danielgaldev** [prettier/prettier-vscode#1207]
**Description of the problem**
I don't have node installed on my computer because I use docker containers for development.  When the extension encounters prettier as a dependency specified in package.json, it tries to load the module and fails, because it does not exist locally or globally.
```
Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install` Attempted to load prettier from package.json
```

**Solution I'd like**
I would like an option to disable this behavior and use the extension instead of the local module.

**Alternatives I've considered**
- Removing prettier from devDependencies in package.json - not an option, since my colleagues use prettier as a local module
- Installing node on my computer - not an option, because I prefer not to clutter my computer with many different dev environments. I work on many projects, I use python, mysql, postgres, java and many others in docker aswell.

**Additional context**
If my problem is not clear, I can provide additional details if needed.

**Comment by David-Else** [comment]
I am now getting this error whatever is in my `package.json`. It is acting like it is using the wrong parser and can't read the JSON. Node 12.4 is installed and working.
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
```
["INFO" - 17:57:24] Extension Name: "prettier-vscode".
["INFO" - 17:57:24] Extension Version: "3.18.0".
["ERROR" - 17:57:24] Failed to load prettier from ''
Unexpected string in JSON at position 205 while parsing '{  "name": "app",  "version": "1.0.0",'
JSONError: Unexpected string in JSON at position 205 while parsing '{  "name": "app",  "version": "1.0.0",'
	at e.exports (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253571)
	at AsyncFunction.e.exports.sync (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253103)
	at AsyncFunction.e.exports.sync (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:249917)
	at t.ModuleResolver.findPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:246650)
	at t.ModuleResolver.findPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:246954)
	at t.ModuleResolver.findPkg [as findPkgMem] (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:247210)
	at t.ModuleResolver.requireLocalPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:245330)
	at t.ModuleResolver.getPrettierInstance (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:243969)
	at t.LanguageResolver.getSupportLanguages (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242420)
	at t.LanguageResolver.allEnabledLanguages (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242028)
	at t.StatusBarService.toggleStatusBarItem (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:85577)
	at new t.StatusBarService (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:85128)
	at t.activate (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:86550)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:911)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:562)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:694:651
	at async Promise.all (index 6)
["ERROR" - 17:57:24] Failed to load prettier from ''
Unexpected string in JSON at position 205 while parsing '{  "name": "app",  "version": "1.0.0",'
JSONError: Unexpected string in JSON at position 205 while parsing '{  "name": "app",  "version": "1.0.0",'
	at e.exports (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253571)
	at AsyncFunction.e.exports.sync (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:253103)
	at AsyncFunction.e.exports.sync (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:249917)
	at t.ModuleResolver.findPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:246650)
	at t.ModuleResolver.findPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:246954)
	at t.ModuleResolver.findPkg [as findPkgMem] (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:247210)
	at t.ModuleResolver.requireLocalPkg (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:245330)
	at t.ModuleResolver.getPrettierInstance (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:243969)
	at t.LanguageResolver.getSupportLanguages (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242420)
	at t.LanguageResolver.allEnabledLanguages (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:242028)
	at t.default.selectors (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:347789)
	at t.default.registerFormatter (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:347056)
	at t.activate (/home/david/.vscode/extensions/esbenp.prettier-vscode-3.18.0/dist/extension.js:1:86609)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:911)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:695:562)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:694:651
	at async Promise.all (index 6)
["INFO" - 17:57:24] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "mongo",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 17:57:24] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
```
```
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 3.18.0
Publisher: Esben Petersen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```

**Comment by ntotten** [comment]
Is setting the `prettierPath` an option? https://github.com/prettier/prettier-vscode#prettierprettierpath

**Comment by danielgaldev** [comment]
@ntotten What should I set the prettier path to? I assume the VSCode plugin is searching for prettier on the host machine, but prettier does not exist on the host machine. It lives inside the docker container.

Another alternative I just thought of is mounting the node_modules of the container to the host machine. The problem with this approach is that moving and deleting projects on my computer becomes tedious, because every project would have its own node_modules in the project directory. It is best practice to keep the node_modules inside the docker container.

**Comment by ntotten** [comment]
Are you using VS Code remote? The extension should work in that scenario as the extension is actually running on the docker container.

**Comment by danielgaldev** [comment]
No, I am using VSCode version 1.41.1 on Windows 10.

**Comment by ntotten** [comment]
Maybe it's not what you want, but have you tried VS Code remote development? That sounds like exactly what you need to get the VS Code features working with docker. https://code.visualstudio.com/docs/remote/containers

This extension works perfectly with remove dev. I did do a bunch of cleanup in the release today that no longer shows the errors unless you actually try to run the formatter. Does that solve the problem or  are you trying to run prettier as well?
