### ISSUE TITLE
Notifying the user of "Error formatting document"

### ISSUE THREAD

**Issue by Nircek** [prettier/prettier-vscode#1419]
Is it possible to notify the user in some way (without checking the Output) when there was a problem with formatting?

**Is your feature request related to a problem? Please describe.**
I have the VS Code with the Prettier extension installed. I'm always frustrated when I don't know why my code is not formatted properly. When I look at the output of Prettier, I see "Error formatting document.". And it pretty always means that I haven't closed one HTML div.

**How to reproduce a problem?**
Create a `test.html` file with this code inside:
```html
<html>
<body>
</html>
```
Open the command palette (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and run `Format document with...` and `Prettier - code formatter`. Now look at the Output (<kbd>Ctrl</kbd>+<kbd>K</kbd> and <kbd>Ctrl</kbd>+<kbd>H</kbd>) in the `Prettier` section. There should be something like that:

```
["INFO" - 13:39:10] Formatting /tmp/test.html
["INFO" - 13:39:10] Using ignore file (if present) at undefined
["INFO" - 13:39:10] Using bundled version of prettier.
["INFO" - 13:39:10] File Info:
{
  "ignored": false,
  "inferredParser": "html"
}
["INFO" - 13:39:10] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 13:39:10] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "/tmp/test.html",
  "parser": "html"
}
["ERROR" - 13:39:10] Error formatting document.
["ERROR" - 13:39:10] Unexpected closing tag "html". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (3:1)
  1 | <html>
  2 | <body>
> 3 | </html>
    | ^
SyntaxError: Unexpected closing tag "html". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (3:1)
  1 | <html>
  2 | <body>
> 3 | </html>
    | ^
    at ct (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/parser-html.js:1:16594)
    at It (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/parser-html.js:113:1296)
    at e (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/parser-html.js:113:3247)
    at Object.parse (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/parser-html.js:113:3724)
    at Object.parse (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:11370:19)
    at coreFormat (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:14784:25)
    at format (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:15019:75)
    at formatWithCursor (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:15035:12)
    at /home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:51620:12
    at Object.format (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/node_modules/prettier/index.js:51640:12)
    at t.default.<anonymous> (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/src/PrettierEditService.ts:328:46)
    at Generator.next (<anonymous>)
    at s (/home/nircek/.vscode-oss/extensions/esbenp.prettier-vscode-5.0.0/dist/extension.js:1:53223)
["INFO" - 13:39:10] Formatting completed in 71.200016ms.
```
But there wasn't any notification for the user and I have to look at the Output.

**Describe the solution you'd like**
The switch in the settings which would turn on notifying the user when an error occurs.

**Additional context**
I have written [the question about this on StackOverflow](https://stackoverflow.com/questions/62261364/is-it-possible-to-notify-the-user-of-error-formatting-document) and got [the reply](https://stackoverflow.com/questions/62261364/is-it-possible-to-notify-the-user-of-error-formatting-document#comment110116122_62261364):
> VSCode API does allow an extension to report errors in better ways (error highlight in the editor, or the Problem tab), so the author of that extension should make use of such.

**Comment by Nircek** [comment]
I can see now that this issue is an exact duplicate of #1332. It can be closed.
