### ISSUE TITLE
Unable to format optional chain operators (?.) in TS,TSX files and null-value merge operator (??)

### ISSUE THREAD

**Issue by joesdu** [prettier/prettier-vscode#1426]
["ERROR" - 上午10:36:50] Expression expected. (29:40)
  27 |           } = response;
  28 |           resolve({
> 29 |             currentUser: { name: name ?? phone, avatar, access },
     |                                        ^
  30 |             settings: defaultSettings
  31 |           });
  32 |         })
SyntaxError: Expression expected. (29:40)
  27 |           } = response;
  28 |           resolve({
> 29 |             currentUser: { name: name ?? phone, avatar, access },
     |                                        ^
  30 |             settings: defaultSettings
  31 |           });
  32 |         })
	at e (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\parser-typescript.js:1:329)
	at Object.parse (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\parser-typescript.js:1:2158501)
	at Object.parse$2 [as parse] (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:10600:19)
	at coreFormat (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:13763:23)
	at format (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:13939:16)
	at formatWithCursor (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:13951:12)
	at c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:41967:15
	at Object.format (c:\Users\joe_du\Documents\GitHub\SmartBuildings\node_modules\prettier\index.js:41986:12)
	at t.default.<anonymous> (c:\Users\joe_du\.vscode-insiders\extensions\esbenp.prettier-vscode-5.0.0\dist\extension.js:1:58458)
	at Generator.next (<anonymous>)
	at s (c:\Users\joe_du\.vscode-insiders\extensions\esbenp.prettier-vscode-5.0.0\dist\extension.js:1:53285)
["INFO" - 上午10:36:50] Formatting completed in 306.2511ms.

### Summary

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/13188169/84459226-78824b00-ac99-11ea-8960-c21cfcee66f2.png)

**VS Code Version**:
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]
版本: 1.47.0-insider (user setup)
提交: 6af2987903c22bf9b19762d589bc46d4be636dc4
日期: 2020-06-11T13:30:35.121Z (13 小时前)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19645

**Prettier Extension Version**: v5.0.0

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREESHOT, COPY AND PASTE THE TEXT
```

**Comment by erodactyl** [comment]
Same issue here, any suggestions?

**Comment by ZakSingh** [comment]
Same issue here for the past week or so

**Comment by ntotten** [comment]
I need the prettier log output.

**Comment by joesdu** [comment]
> I need the prettier log output.

["INFO" - 上午12:57:39] Extension Name: esbenp.prettier-vscode.
["INFO" - 上午12:57:39] Extension Version: 5.0.0.
["INFO" - 上午12:57:39] Loaded module 'prettier@1.15.3' from 'g:\GitHub\SmartBuildings\node_modules\prettier\index.js'
["INFO" - 上午12:57:39] Enabling prettier for languages
[
  "css",
  "graphql",
  "html",
  "javascript",
  "javascriptreact",
  "json",
  "json5",
  "jsonc",
  "less",
  "markdown",
  "mdx",
  "postcss",
  "scss",
  "typescript",
  "typescriptreact",
  "vue",
  "yaml"
]
["INFO" - 上午12:57:39] Enabling prettier for range supported languages
[
  "graphql",
  "javascript",
  "javascriptreact",
  "json",
  "typescript",
  "typescriptreact"
]
["INFO" - 上午12:58:03] Formatting g:\GitHub\SmartBuildings\src\app.tsx
["INFO" - 上午12:58:03] Using ignore file (if present) at g:\GitHub\SmartBuildings\.prettierignore
["INFO" - 上午12:58:03] Loaded module 'prettier@1.15.3' from 'g:\GitHub\SmartBuildings\node_modules\prettier\index.js'
["INFO" - 上午12:58:03] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 上午12:58:04] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 上午12:58:04] Prettier Options:
{
  "filepath": "g:\\GitHub\\SmartBuildings\\src\\app.tsx",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "singleQuote": true,
  "trailingComma": "none",
  "printWidth": 200,
  "proseWrap": "never"
}
["ERROR" - 上午12:58:05] Error formatting document.
["ERROR" - 上午12:58:05] Expression expected. (29:40)
  27 |           } = response;
  28 |           resolve({
> 29 |             currentUser: { name: name ?? phone, avatar, access },
     |                                        ^
  30 |             settings: defaultSettings
  31 |           });
  32 |         })
SyntaxError: Expression expected. (29:40)
  27 |           } = response;
  28 |           resolve({
> 29 |             currentUser: { name: name ?? phone, avatar, access },
     |                                        ^
  30 |             settings: defaultSettings
  31 |           });
  32 |         })
	at e (g:\GitHub\SmartBuildings\node_modules\prettier\parser-typescript.js:1:329)
	at Object.parse (g:\GitHub\SmartBuildings\node_modules\prettier\parser-typescript.js:1:2158501)
	at Object.parse$2 [as parse] (g:\GitHub\SmartBuildings\node_modules\prettier\index.js:10600:19)
	at coreFormat (g:\GitHub\SmartBuildings\node_modules\prettier\index.js:13763:23)
	at format (g:\GitHub\SmartBuildings\node_modules\prettier\index.js:13939:16)
	at formatWithCursor (g:\GitHub\SmartBuildings\node_modules\prettier\index.js:13951:12)
	at g:\GitHub\SmartBuildings\node_modules\prettier\index.js:41967:15
	at Object.format (g:\GitHub\SmartBuildings\node_modules\prettier\index.js:41986:12)
	at t.default.<anonymous> (c:\Users\joe_du\.vscode-insiders\extensions\esbenp.prettier-vscode-5.0.0\dist\extension.js:1:58458)
	at Generator.next (<anonymous>)
	at s (c:\Users\joe_du\.vscode-insiders\extensions\esbenp.prettier-vscode-5.0.0\dist\extension.js:1:53285)
["INFO" - 上午12:58:05] Formatting completed in 601.618599ms.

**Comment by ntotten** [comment]
You are using a very old version of prettier that does not support those operators:

`["INFO" - 上午12:58:03] Loaded module 'prettier@1.15.3' from 'g:\GitHub\SmartBuildings\node_modules\prettier\index.js'`

Upgrade to the latest version of prettier.

**Comment by joesdu** [comment]
> You are using a very old version of prettier that does not support those operators:
> 
> `["INFO" - 上午12:58:03] Loaded module 'prettier@1.15.3' from 'g:\GitHub\SmartBuildings\node_modules\prettier\index.js'`
> 
> Upgrade to the latest version of prettier.

thanks very much!
