### ISSUE TITLE
Extensions does not work with YARN PnP

### ISSUE THREAD

**Issue by abdes** [prettier/prettier-vscode#1502]
### Summary

Yarn PnP does not have a node_modules in the workspace folder. The extension attempts to do its own resolution to load prettier and its plugins from the workspace in an incompatible way with YARN PnP.

Doing a npm install in the same project to just create a node_modules and populate it fixes the issue for prettier extension. But that is not the point, right :-). Yarn PnP does not need a node_modules.

### Steps To Reproduce:

1. Any new project with yarn berry (yarn v2) for an out of the box PnP setup
1. Add prettier and plugins to package.json
1. Configure vscode to work with yarn berry: https://yarnpkg.com/advanced/editor-sdks#vscode
1. start vscode => format any file with prettier extension

### Expected result

No errors and file formatted properly.
Note that prettier from the command line in the same environment with PnP works perfectly fine.

### Actual result

The result is:

```
["ERROR" - 8:35:50 PM] Cannot find module 'prettier' from 'e:\dev\projects\yarn-workspaces\yarn-dep-graph'
Error: Cannot find module 'prettier' from 'e:\dev\projects\yarn-workspaces\yarn-dep-graph'
	at Function.e.exports [as sync] (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:44268)
	at t.ModuleResolver.findPkg (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:30336)
	at t.ModuleResolver.findPkg [as findPkgMem] (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:33675)
	at t.ModuleResolver.requireLocalPkg (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:28684)
	at t.ModuleResolver.getPrettierInstance (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:27415)
	at t.LanguageResolver.getSupportLanguages (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:25522)
	at t.LanguageResolver.allEnabledLanguages (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:25231)
	at t.default.selectors (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:54753)
	at registerFormatter (c:\Users\USER\.vscode\extensions\esbenp.prettier-vscode-5.1.3\dist\extension.js:1:54055)
	at l.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:661:802
	at l.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at t.ExtHostFileSystemEventService.$onFileEvent (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:663:41)
	at m._doInvokeHandler (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:683)
	at m._invokeHandler (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:801:375)
	at m._receiveRequest (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:14)
	at m._receiveOneMessage (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:832)
	at e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:797:34
	at l.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:744
	at l.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:276)
	at e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:237:357
	at l.fire (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:393)
	at e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:232:753
	at Socket.t (e:\dev\vscode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:241:826)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
["INFO" - 8:35:50 PM] Enabling prettier for languages
```

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.47.3

**Prettier Extension Version**: v5.1.3

**OS and version**: Windows 10

**Comment by ntotten** [comment]
This seems to be a bug on Prettier itself. Prettier alone works as expected in both vscode and through the CLI when I use PnP as documented here: https://yarnpkg.com/advanced/editor-sdks#vscode. However, when I install a plugin prettier fails to resolve it in either the CLI or VS Code.

**Comment by jackgeek** [comment]
For anyone looking for a solution.  I found this which helped:
https://github.com/prettier/prettier-vscode/issues/1066#issuecomment-561709876

**Comment by jamesmarkcook** [comment]
Yarn pnp now supports this plugin. As @ntotten suggests above visit https://yarnpkg.com/advanced/editor-sdks#vscode for full details.

The line you want to run in your terminal inside your project dir is:

```bash
yarn dlx @yarnpkg/pnpify --sdk vscode
```

This does some magic to tell the prettier-vscode plugin where to find the local prettier module.
