### ISSUE TITLE
Prettier can't resolve global packages as configuration

### ISSUE THREAD

**Issue by yordis** [prettier/prettier-vscode#1540]
### Summary

I have a global `$HOME/.prettierrc.json` that uses a package as the base configuration. The extension fails unless I add such package, and the `.prettierrc.json` locally to the project.

### Github Repository to Reproduce Issue

```bash
mkdir test123
cd test123
yarn init
```

### Steps To Reproduce:

1.  Install the following packages globally: `yarn global add prettier @straw-hat/prettier-config`.
2. Create a project
    ```bash
    mkdir test123
    cd test123
    yarn init
    ```
3. Create `$HOME/.prettierrc.json` file with the following content
    ```json
    "@straw-hat/prettier-config"
    ```
3. Notice the error

### Expected result

I would expect the Node Modules resolution to work and be able to find `@straw-hat/prettier-config` global package.

### Actual result

The extension can't find the global package.

### Additional information

**VS Code Version**: 1.48.2

**Prettier Extension Version**: v5.5.0

**OS and version**: MacOS 10.15.3

## Prettier Log Output

```
["ERROR" - 9:00:44 PM] Invalid prettier configuration file detected.
["ERROR" - 9:00:44 PM] Cannot find module '@straw-hat/prettier-config' from '/Users/ubi'
Error: Cannot find module '@straw-hat/prettier-config' from '/Users/ubi'
	at Function.resolveSync [as sync] (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/index.js:20665:13)
	at resolve$1 (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/index.js:20803:20)
	at Object.transform (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/index.js:25221:30)
	at run (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9859:51)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async cacheWrapper (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9711:20)
	at async Explorer.search (/Users/ubi/.vscode/extensions/esbenp.prettier-vscode-5.5.0/node_modules/prettier/third-party.js:9844:22)
	at async Promise.all (index 0)
```

**Comment by ntotten** [comment]
This probably is a bug, but global installs of prettier is actually not a supported solution. I will probably be removing it as an option in this extension in a future version as well. See: https://prettier.io/docs/en/install.html

**Comment by yordis** [comment]
@ntotten is there any particular reason why you wouldn't support it?

The intent form our side is that people don't need to install either `prettier` or the configuration in each project, so we need this feature.

**Comment by ntotten** [comment]
npm & prettier recommend against using global packages.
