### ISSUE TITLE
Error formatting document

### ISSUE THREAD

**Issue by jmls** [prettier/prettier-vscode#1552]
### Summary

prettier does not format a document on save,

### Github Repository to Reproduce Issue

private repo

### Steps To Reproduce:

1.  add a comment to typescript code (/* fixme */)
2. save the file
3. file is not formatted

### Expected result

file should be formatted

### Actual result

file is not formatted

### Additional information

in the "output" tab there is a prettier error
(see log below)

**VS Code Version**:
1.49 insider
**Prettier Extension Version**:
v5.5.0
**OS and version**:
vscode remote docker container
## Prettier Log Output

["ERROR" - 5:42:36 PM] Error formatting document.
["ERROR" - 5:42:36 PM] Comment "fixme" was not printed. Please report this error!
Error: Comment "fixme" was not printed. Please report this error!
	at /workspace/node_modules/prettier/index.js:14753:13
	at Array.forEach (<anonymous>)
	at ensureAllCommentsPrinted (/workspace/node_modules/prettier/index.js:14751:15)
	at coreFormat (/workspace/node_modules/prettier/index.js:14799:3)
	at format (/workspace/node_modules/prettier/index.js:15017:75)
	at formatWithCursor (/workspace/node_modules/prettier/index.js:15033:12)
	at /workspace/node_modules/prettier/index.js:50675:12
	at Object.format (/workspace/node_modules/prettier/index.js:50695:12)
	at t.default.<anonymous> (/root/.vscode-server-insiders/extensions/esbenp.prettier-vscode-5.5.0/dist/extension.js:1:59917)
	at Generator.next (<anonymous>)
	at s (/root/.vscode-server-insiders/extensions/esbenp.prettier-vscode-5.5.0/dist/extension.js:1:54201)

**Comment by ntotten** [comment]
This is an issue for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.
