### ISSUE TITLE
Still problems with yarn PnP

### ISSUE THREAD

**Issue by gunters63** [prettier/prettier-vscode#1730]
### Summary

I still can't get prettier to work correctly with the vscode-plugin, it reverts to the built-in version because of an exception

### Steps To Reproduce:

1.  Try to format a Javascript or Typescript file, the plugin will use the built-in version of prettier instead the one installed in th workspace (with yarn PnP)

### Expected result

The extension should be able to use the prettier version in the workspace and use its settings

### Actual result

Extension uses the built-in prettier

### Additional information

I did install the yarn pnp editor sdk:

```
yarn dlx @yarnpkg/pnpify --sdk vscode
```

Output:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 3s 769ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 288ms
➤ YN0000: Done in 4s 205ms

➤ YN0000: Cleaning up the existing SDK files...
➤ YN0000: ┌ Generating SDKs inside .yarn/sdks
➤ YN0000: │ ✓ Eslint
➤ YN0000: │ ✓ Prettier
➤ YN0000: │ ✓ Typescript
➤ YN0000: │ • 4 SDKs were skipped based on your root dependencies
➤ YN0000: └ Completed
➤ YN0000: ┌ Generating settings
➤ YN0000: │ ✓ Vscode (updated 🔼)
➤ YN0000: └ Completed
```

Relevant packages in package.json:

```
    "@yarnpkg/pnpify": "^2.4.0",
    "prettier": "^2.2.1",
```

prettier from the command line works fine, run it with the following npm script:

```
    "format": "prettier --write src/**/*.ts{,x}",
```

**VS Code Version**: 1.52.1

**Prettier Extension Version**: 5.8.0

**OS and version**: Windows 10

## Prettier Log Output

```
["INFO" - 11:24:36] Extension Name: esbenp.prettier-vscode.
["INFO" - 11:24:36] Extension Version: 5.8.0.
["ERROR" - 11:24:36] Error loading node module 'prettier'
["ERROR" - 11:24:36] Cannot find module '@yarnpkg/pnpify'
Require stack:
- d:\proj\AtlasCopco\ensoui-prototype\.yarn\sdks\prettier\internal.js
Require stack:
- d:\proj\AtlasCopco\ensoui-prototype\.yarn\sdks\prettier\index.js
- c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
Error: Cannot find module '@yarnpkg/pnpify'
Require stack:
- d:\proj\AtlasCopco\ensoui-prototype\.yarn\sdks\prettier\internal.js
Require stack:
- d:\proj\AtlasCopco\ensoui-prototype\.yarn\sdks\prettier\index.js
- c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
	at Function.external_module_.Module._resolveFilename (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:33768:46)
	at callNativeResolution (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:34182:36)
	at resolveToUnqualified (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:34389:24)
	at resolveRequest (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:34641:29)
	at Object.resolveRequest (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:34719:26)
	at Function.external_module_.Module._resolveFilename (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:33817:34)
	at Function.r.resolve (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:406)
	at Object.<anonymous> (d:\proj\AtlasCopco\ensoui-prototype\.yarn\sdks\prettier\index.js:18:36)
	at Module.o._compile (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Module._load (electron/js2c/asar.js:769:28)
	at t._load (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1092:657)
	at i._load (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1061:334)
	at n._load (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1057:567)
	at Function.external_module_.Module._load (d:\proj\AtlasCopco\ensoui-prototype\.pnp.js:33676:36)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:346)
	at t.ModuleResolver.loadNodeModule (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:8788)
	at t.ModuleResolver.requireLocalPkg (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:7919)
	at t.ModuleResolver.getPrettierInstance (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:6604)
	at t.LanguageResolver.getSupportLanguages (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:4679)
	at t.LanguageResolver.getSupportedLanguages (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:4210)
	at t.default.selectors (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:13240)
	at t.default.registerFormatter (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:12457)
	at t.activate (c:\Users\retnu\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:21805)
	at Function._callActivateOptional (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:960:773)
	at Function._callActivate (c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:960:424)
	at c:\Users\retnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:958:841
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
```

**Comment by gunters63** [comment]
Content of .yarn\sdks\prettier\index.js for reference:

```
#!/usr/bin/env node

const {existsSync} = require(`fs`);
const {createRequire, createRequireFromPath} = require(`module`);
const {resolve, dirname} = require(`path`);

const relPnpApiPath = "../../../.pnp.js";

const absPnpApiPath = resolve(__dirname, relPnpApiPath);
const absRequire = (createRequire || createRequireFromPath)(absPnpApiPath);

if (existsSync(absPnpApiPath)) {
  if (!process.versions.pnp) {
    // Setup the environment to be able to require prettier/index.js
    require(absPnpApiPath).setup();
  }

  const pnpifyResolution = require.resolve(`@yarnpkg/pnpify`, {paths: [dirname(absPnpApiPath)]});
  if (typeof global[`__yarnpkg_sdk_is_using_pnpify__`] === `undefined`) {
    Object.defineProperty(global, `__yarnpkg_sdk_is_using_pnpify__`, {configurable: true, value: true});

    process.env.NODE_OPTIONS += ` -r ${pnpifyResolution}`;

    // Apply PnPify to the current process
    absRequire(pnpifyResolution).patchFs();
  }
}

// Defer to the real prettier/index.js your application uses
module.exports = absRequire(`prettier/index.js`);

```

**Comment by gunters63** [comment]
It seems this specific problem is a problem of yarn 2 prettier SDK: See [[Bug] Prettier is unable to load plugins in PNP environment](https://github.com/yarnpkg/berry/issues/1903)

If I manually change my prettier sdk script to the one posted at the end of this thread, the plugin seems to work.
I think the next yarn 2 update should fix the problem then.

I will close the issue again.
