### ISSUE TITLE
Template string type caused format error in `extends' statement

### ISSUE THREAD

**Issue by TheNightmareX** [prettier/prettier-vscode#1772]
### Summary

It seems that the template string type in typescript will cause format error in `extends` statements.

### Steps To Reproduce:

```TypeScript
type Type<T> = T extends string ? `string` : `other`;
```

### Expected result

The type is allowed in typescript, and the my code should be formatted.

### Actual result

But it actually cause a format error, and my code didn't be formatted at all.

### Additional information

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
["INFO" - 上午10:10:04] Formatting c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\src\api\test.ts
["INFO" - 上午10:10:04] Using ignore file (if present) at c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\.prettierignore
["INFO" - 上午10:10:04] Loaded module 'prettier@1.19.1' from 'c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js'
["INFO" - 上午10:10:04] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 上午10:10:04] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 上午10:10:04] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "c:\\Users\\TheNightmareX\\Desktop\\ts\\ChaaAt_frontend\\src\\api\\test.ts",
  "parser": "typescript"
}
["ERROR" - 上午10:10:04] Error formatting document.
["ERROR" - 上午10:10:04] '?' expected. (1:35)
> 1 | type Type<T> = T extends string ? `string` : `other`;
    |                                   ^
  2 | 
  3 | 
  4 | 
SyntaxError: '?' expected. (1:35)
> 1 | type Type<T> = T extends string ? `string` : `other`;
    |                                   ^
  2 | 
  3 | 
  4 | 
	at t (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\parser-typescript.js:1:347)
	at Object.parse (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\parser-typescript.js:14:180461)
	at Object.parse (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:9739:19)
	at coreFormat (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:13252:23)
	at format (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:13510:73)
	at formatWithCursor (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:13526:12)
	at c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:44207:15
	at Object.format (c:\Users\TheNightmareX\Desktop\ts\ChaaAt_frontend\node_modules\prettier\index.js:44226:12)
	at t.default.<anonymous> (c:\Users\TheNightmareX\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:17599)
	at Generator.next (<anonymous>)
	at s (c:\Users\TheNightmareX\.vscode\extensions\esbenp.prettier-vscode-5.8.0\dist\extension.js:1:11597)
["INFO" - 上午10:10:04] Formatting completed in 19.5712ms.
```

**Comment by ntotten** [comment]
You have an old version of prettier or typescript configure on your project.
