### ISSUE TITLE
Comment 'x' was not printed

### ISSUE THREAD

**Issue by trumbitta** [prettier/prettier-vscode#1872]
### Summary

If my React TypeScript file has comments, prettier-vscode exits with error, blaming Prettier

Just like: #1552 
Plot twist: https://github.com/prettier/prettier/issues/10592

and now I'm confused

### Actual result

```
["INFO" - 12:24:50 PM] Formatting /redacted.tsx
["INFO" - 12:24:50 PM] Using config file at '/redacted/.prettierrc'
["INFO" - 12:24:50 PM] Using ignore file (if present) at /redacted/.prettierignore
["INFO" - 12:24:50 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 12:24:50 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:24:50 PM] Prettier Options:
{
  "filepath": "/redacted.tsx",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": true,
  "trailingComma": "all",
  "printWidth": 120
}
["ERROR" - 12:24:50 PM] Error formatting document.
["ERROR" - 12:24:50 PM] Comment "Third Parties" was not printed. Please report this error!
Error: Comment "Third Parties" was not printed. Please report this error!
	at /redacted/node_modules/prettier/index.js:14753:13
	at Array.forEach (<anonymous>)
	at ensureAllCommentsPrinted (/redacted/node_modules/prettier/index.js:14751:15)
	at coreFormat (/redacted/node_modules/prettier/index.js:14799:3)
	at format (/redacted/node_modules/prettier/index.js:15017:75)
	at formatWithCursor (/redacted/node_modules/prettier/index.js:15033:12)
	at /redacted/node_modules/prettier/index.js:50675:12
	at Object.format (/redacted/node_modules/prettier/index.js:50695:12)
	at t.default.<anonymous> (/redacted/.vscode/extensions/esbenp.prettier-vscode-6.3.1/dist/extension.js:1:16946)
	at Generator.next (<anonymous>)
	at s (/redacted/.vscode/extensions/esbenp.prettier-vscode-6.3.1/dist/extension.js:1:9119)
["INFO" - 12:24:50 PM] Formatting completed in 35.601617ms.

```

### Additional information

**VS Code Version**: 1.54.3

**Prettier Extension Version**: v6.3.1

**OS and version**: macOS 11.2.3

**Comment by trumbitta** [comment]
I reloaded the window (Developer: reload window) and the error vanished. 🤷

**Comment by ntotten** [comment]
This is an issue or feature request for the Prettier library itself rather than the VS Code extension for prettier. Please open an issue at https://github.com/prettier/prettier.

**Comment by trumbitta** [comment]
Yeah, Prettier guys replied the same about this repo 🤷

**Comment by thorn0** [comment]
> Yeah, Prettier guys replied the same about this repo

That didn't happen though.

**Comment by trumbitta** [comment]
It seems you are right.

Apologies. I guess the pandemic is finally starting to make my mind play tricks on me.
