### ISSUE TITLE
Prettier is work in other folder, but only didn't work in webpack folder.

### ISSUE THREAD

**Issue by lovefields** [prettier/prettier-vscode#1909]
### Summary

Prettier is work in other folder, but only didn't work in webpack folder.

### Github Repository to Reproduce Issue

Sorry, my repository is private.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.55.2

**Prettier Extension Version**: 6.3.2.

**OS and version**: maxOs Big Sur 11.2.3

## Prettier Log Output

```
["ERROR" - 10:14:50 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 10:14:50 AM] Cannot find module 'prettier' from '[mydir]/webpack'
Error: Cannot find module 'prettier' from '[mydir]/webpack'
	at Function.e.exports [as sync] ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:44001)
	at t.ModuleResolver.findPkg ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:7906)
	at t.ModuleResolver.<anonymous> ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:4031)
	at Generator.next (<anonymous>)
	at [userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:2893
	at new Promise (<anonymous>)
	at n ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:2638)
	at t.ModuleResolver.getPrettierInstance ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:3852)
	at t.default.<anonymous> ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:15794)
	at Generator.next (<anonymous>)
	at s ([userFolder]/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:9119)
["ERROR" - 10:14:50 AM] Prettier could not be loaded. See previous logs for more information.
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
