### ISSUE TITLE
Error when format with ?. in ts file

### ISSUE THREAD

**Issue by denghui1010** [prettier/prettier-vscode#1980]
### Summary

error when i use ?. in .ts file

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1. copy this code to a ts file
  ```
  interface Provide {
    obj?: { b: string };
  }
  
  const a: Provide = {obj: undefined}
  
  console.log(a.obj?.b);
  ```
2. format code

### Expected result

format success

### Actual result

error and not format

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
版本: 1.56.2
提交: 054a9295330880ed74ceaedda236253b4f39a335
日期: 2021-05-12T17:44:30.902Z (2 周前)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

**Prettier Extension Version**:
Extension Version: 6.4.0

**OS and version**:
macOS Catalina 10.15.7

## Prettier Log Output

```
["INFO" - 12:55:21 PM] Formatting /Users/liudenghui/workspace/qprojects/...
["INFO" - 12:55:21 PM] Using config file at '/Users/liudenghui/workspace/qprojects/.../.prettierrc'
["INFO" - 12:55:21 PM] Using ignore file (if present) at /Users/liudenghui/workspace/qprojects/.../.prettierignore
["INFO" - 12:55:21 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 12:55:21 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:55:21 PM] Prettier Options:
{
  "filepath": "/Users/liudenghui/workspace/qprojects/.../index.tsx",
  "parser": "typescript",
  "indentWidth": 2,
  "printWidth": 120,
  "singleQuote": true
}
["ERROR" - 12:55:21 PM] Error formatting document.
["ERROR" - 12:55:21 PM] Expression expected. (47:19)
  45 | const a: Provide = {obj: undefined}
  46 | 
> 47 | console.log(a.obj?.b);
     |                   ^
  48 | 
SyntaxError: Expression expected. (47:19)
  45 | const a: Provide = {obj: undefined}
  46 | 
> 47 | console.log(a.obj?.b);
     |                   ^
  48 | 
	at e (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/parser-typescript.js:1:329)
	at Object.parse (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/parser-typescript.js:1:2172609)
	at Object.parse$2 [as parse] (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:10629:19)
	at coreFormat (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:13846:23)
	at format (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:14105:73)
	at formatWithCursor (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:14121:12)
	at /Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:42389:15
	at Object.format (/Users/liudenghui/workspace/qprojects/.../node_modules/prettier/index.js:42408:12)
	at t.default.<anonymous> (/Users/liudenghui/.vscode/extensions/esbenp.prettier-vscode-6.4.0/dist/extension.js:1:16819)
	at Generator.next (<anonymous>)
	at s (/Users/liudenghui/.vscode/extensions/esbenp.prettier-vscode-6.4.0/dist/extension.js:1:9119)
["INFO" - 12:55:21 PM] Formatting completed in 17.127367ms.

```

**Comment by denghui1010** [comment]
Format success when I upgrade the prettier version to 2.3.0
