### ISSUE TITLE
Prettier formatting is not working on apex classes

### ISSUE THREAD

**Issue by SagarSfdc** [prettier/prettier-vscode#1999]
["INFO" - 9:17:50 pm] Formatting g:\Vs-Code\Project\force-app\main\default\classes\SampleAddress.cls
["INFO" - 9:17:50 pm] Using config file at 'g:\Vs-Code\Project\.prettierrc'
["INFO" - 9:17:50 pm] Using ignore file (if present) at g:\Vs-Code\Project\.prettierignore
["INFO" - 9:17:50 pm] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 9:17:50 pm] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 9:17:50 pm] Prettier Options:
{
  "filepath": "g:\\Vs-Code\\Project\\force-app\\main\\default\\classes\\SampleAddress.cls",
  "parser": "apex",
  "trailingComma": "none"
}
["ERROR" - 9:17:52 pm] Error formatting document.
Error: 
	at parseTextWithSpawn (g:\Vs-Code\Project\node_modules\prettier-plugin-apex\src\parser.js:36:11)
	at Object.parse (g:\Vs-Code\Project\node_modules\prettier-plugin-apex\src\parser.js:489:21)
	at Object.parse$a [as parse] (g:\Vs-Code\Project\node_modules\prettier\index.js:13652:19)
	at coreFormat (g:\Vs-Code\Project\node_modules\prettier\index.js:15183:16)
	at formatWithCursor$1 (g:\Vs-Code\Project\node_modules\prettier\index.js:15423:14)
	at g:\Vs-Code\Project\node_modules\prettier\index.js:60171:12
	at Object.format (g:\Vs-Code\Project\node_modules\prettier\index.js:60191:12)
	at t.default.<anonymous> (c:\Users\Sagar\.vscode\extensions\esbenp.prettier-vscode-6.4.0\dist\extension.js:1:16819)
	at Generator.next (<anonymous>)
	at s (c:\Users\Sagar\.vscode\extensions\esbenp.prettier-vscode-6.4.0\dist\extension.js:1:9119)
["INFO" - 9:17:52 pm] Formatting completed in 685.5813ms.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by SagarSfdc** [comment]
I found the thread https://github.com/dangmai/prettier-plugin-apex/issues/357 so this was due to the older version of JDK. Updated the JDK and it worked.

Hence closing the issue.

> This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.
