### ISSUE TITLE
Extension does not load, "Cannot find module 'prettier'" after v7.0.0 update

### ISSUE THREAD

**Issue by jakebailey** [prettier/prettier-vscode#2012]
### Summary

After the v7.0.0 update, the extension no longer formats anything, instead throwing an error.

### Github Repository to Reproduce Issue

This happens to any and all code I try to format, but this is on https://github.com/microsoft/pyright, which uses 

### Steps To Reproduce:

1.  Open any TS file.
1.  Hit enter a few times to make a change
1.  Save.

### Expected result

Code is reformatted back.

### Actual result

The code is not changed, and I see an error message.

The developer console says that the extension failed to load:

```
workbench.desktop.main.js:sourcemap:2465 Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'prettier'
Require stack:
- c:\Users\jabaile\.vscode\extensions\esbenp.prettier-vscode-7.0.0\dist\extension.js
- c:\Users\jabaile\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\jabaile\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\jabaile\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

### Additional information

![image](https://user-images.githubusercontent.com/5341706/122833838-77b7c800-d2a2-11eb-8fdc-372847e4f378.png)

**VS Code Version**: 1.57.1.

**Prettier Extension Version**: v7.0.0

**OS and version**: Windows 10.

```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

## Prettier Log Output

The extension does not activate, so no logs appear that can be copied; the developer tools do have logs, though (see above).

**Comment by jspencev** [comment]
Error:

```
[2021-06-21 15:14:25.096] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-21 15:14:25.096] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- /Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.2392 (/Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72632)
	at r (/Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72851)
	at Object.9854 (/Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:1392)
	at r (/Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72851)
	at /Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:73022
	at /Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:74003
	at Object.<anonymous> (/Users/me/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:74024)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at m._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25973)
	at m._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12617)
	at m._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11676)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
```

**Comment by BitPatty** [comment]
Workaround: https://github.com/prettier/prettier-vscode/issues/2013#issuecomment-865381924

**Comment by ntotten** [comment]
Changes from 7.0.0 were reverted and a new version 7.1.0 was published.
