### ISSUE TITLE
v7.0.0 doesn't seem to work

### ISSUE THREAD

**Issue by sethvargo** [prettier/prettier-vscode#2013]
### Summary

Upgrading to v7.0.0 causes prettier-vscode to stop working with the following error in the status bar:

```text
Extension 'Prettier - Code formatter' cannot format 'index.js'
```

Downgrading to v6.4.0 works fine.

### GitHub Repository to Reproduce Issue

N/A - happens on any js file:

```javascript
function foo() {
  console.log('hi');
}
```

### Steps To Reproduce:

1. Install v7.0.0
1. Try to run the formatter
1. Get error

### Expected result

Prettier v7.0.0 should work as v6.4.0.

### Actual result

Prettier v7.0.0 does not format and prints an error in the status bar.

### Additional information

![CleanShot 2021-06-21 at 18 09 01@2x](https://user-images.githubusercontent.com/408570/122833966-c9208100-d2bb-11eb-86d3-d0a5cce450f6.png)

**VS Code Version**:

```text
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

**Prettier Extension Version**:

```
v7.0.0
```

**OS and version**:

```text
OS: Darwin x64 20.5.0
```

## Prettier Log Output

**There are no logs on v7.0.0. Prettier never appears in the status bar.** Downgrading to v6.4.0 brings it back and shows logs.

**Comment by BitPatty** [comment]
Prettier fails to load the prettier module.

Tested on locally Windows, via WSL2, in a Debian Container and on Codespaces, same issue on all extension hosts..

6.4.0:
```
[2021-06-21 22:12:19.935] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-06-21 22:12:19.935] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/node/.vscode-remote/extensions/esbenp.prettier-vscode-6.4.0/dist/extension
```

7.0.0:
```
2021-06-21 22:14:20.991] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-21 22:14:20.992] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- /home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js
- /home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/loader.js
- /home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/bootstrap-amd.js
- /home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.n._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:103:27815)
    at Function.E._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:103:24567)
    at Function.c._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.call (/home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/external "prettier":1:18)
    at r (/home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/webpack/bootstrap:19:32)
    at Object.call (/home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/src/LoggingService.ts:1:1)
    at r (/home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/webpack/bootstrap:19:32)
    at /home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/src/extension.ts:3:1
    at /home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:73941
    at Object.<anonymous> (/home/node/.vscode-remote/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:73962)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.n._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:103:27815)
    at Function.E._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:103:24567)
    at Function.c._load (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.t [as __$__nodeRequire] (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/loader.js:5:101)
    at m._loadCommonJSModule (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:103:25973)
    at m._doActivateExtension (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:12617)
    at m._activateExtension (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:11676)
    at Object.actualActivateExtension (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:9261)
    at l._activateExtension (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:84:85440)
    at /home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:84:85122
    at Array.map (<anonymous>)
    at l._activateExtensions (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:84:85110)
    at l.activateById (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:84:82740)
    at m._activateById (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:10223)
    at m._activateOneStartupFinished (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:15197)
    at m._activateAllStartupFinished (/home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:15568)
    at /home/node/.vscode-remote/bin/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/server/remoteExtensionHostProcess.js:89:16057
```

**Comment by stevehanson** [comment]
I got around this for now by downgrading to 6.4:

![image](https://user-images.githubusercontent.com/1691324/122834705-af2f7000-d2b4-11eb-87dd-a720d608af82.png)

**Comment by uknowsam** [comment]
> 
> 
> For anyone else facing this, I got around it for now by downgrading the plugin back to 6.4:
> 
> ![image](https://user-images.githubusercontent.com/1691324/122834705-af2f7000-d2b4-11eb-87dd-a720d608af82.png)

Works for me. Thanks!

**Comment by Codex-** [comment]
Experiencing the same issue here

**Comment by jzamora5** [comment]
Same issue happening to me in WSL 2 Ubuntu 20

**Comment by hesto2** [comment]
Running into this with WSL2 Ubuntu 20 as well

**Comment by SleeplessByte** [comment]
Apart from "it not working" I've noticed a few specific things: 

- `ebsenp.prettier-vscode` is no longer showing as valid option for Editor: Default formatter.
- It's not showing in the Output tab as extension log
- It's not registered as a "language" formatted (e.g. it doesn't show up as option for `json`)
- As everyone here has mentioned, it just fails to run

**Comment by mgabeler-lee-6rs** [comment]
It looks like the extension packaging/upload excluded the `node_modules` directory. Looking at the v6.4.0 version of `package.json`, I'd believe all the dependencies were provided by VScode itself. But now it has some very real dependencies it needs to ship.

I think this line is excluding `node_modules` from the webpack: https://github.com/prettier/prettier-vscode/blob/main/webpack.config.js#L49 ... though I'm not sure including prettier in the webpack is the right thing to do :man_shrugging:

**Comment by n8isjack** [comment]
Bless you! Pulled my hair out this morning. I might be too dependent on prettier :)

This worked for me. v7 was not working.

**Comment by ntotten** [comment]
Changes from 7.0.0 were reverted and a new version 7.1.0 was published.

**Comment by sethvargo** [comment]
Thank you @ntotten for the fix and rapid response!

**Comment by mgabeler-lee-6rs** [comment]
@ntotten version 8.0.0 seems to be right back where we were with this ticket. `node_modules` isn't bundled, and so we're right back where we were before
