### ISSUE TITLE
Extension 'Prettier - Code formatter' cannot format 'src/Home.js'

### ISSUE THREAD

**Issue by richard12511** [prettier/prettier-vscode#2014]
Just started happening today. I see that message at the bottom of vscode when I save the file. Seems latest update may have broken it.

<img width="442" alt="Screen Shot 2021-06-21 at 5 58 26 PM" src="https://user-images.githubusercontent.com/14022977/122837891-88743800-d2ba-11eb-85dd-1ead28b42796.png">

Not a gamebreaking bug, but it was super convenient to be able to auto format code.

**Comment by KoichaDev** [comment]
Yeah I also notice this issue!

**Comment by PierreAndreis** [comment]
```
[2021-06-21 20:11:25.860] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-21 20:11:25.860] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- /home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js
- /snap/code/67/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/67/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/67/usr/share/code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.n._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
    at Function.E._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
    at Function.c._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/snap/code/67/usr/share/code/resources/app/out/vs/loader.js:4:698)
    at Object.2392 (/home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72632)
    at r (/home/zeeh/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72851)
    at Object.9854 (/home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:1392)
    at r (/home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:72851)
    at /home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:73022
    at /home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:74003
    at Object.<anonymous> (/home/--/.vscode/extensions/esbenp.prettier-vscode-7.0.0/dist/extension.js:1:74024)
    at Module.u._compile (/snap/code/67/usr/share/code/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.n._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
    at Function.E._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
    at Function.c._load (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.t [as $nodeRequire] (/snap/code/67/usr/share/code/resources/app/out/vs/loader.js:5:101)
    at m._loadCommonJSModule (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25973)
    at m._doActivateExtension (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12617)
    at m._activateExtension (/snap/code/67/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11676)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)```

**Comment by michaeltroya** [comment]
Looks like there is a bug with version 7.0.0 the fix for me was downgrading my extension to 6.4.0. 

You can downgrade by going to the Prettier extension and clicking the dropdown next to uninstall.

**Comment by ntotten** [comment]
Changes from 7.0.0 were reverted and a new version 7.1.0 was published.

**Comment by ConsoleTVs** [comment]
@ntotten 

> Error while installing 'Prettier - Code formatter' extension. Please check the log for more details.

Installing Extension Prettier - Code formatter failed: Manifest is not found.

**Comment by richard12511** [comment]
Looks like I'm still getting the same error in 8.0.0.

Going back to version 6.4.0 fixes the issue. As @michaeltroya mentioned.

**Comment by sumirart** [comment]
going back to 7.1.1 version solved my error
