### ISSUE TITLE
Prettier does not work on VSCode installed via unpacking .tar.gz

### ISSUE THREAD

**Issue by Nikki1993** [prettier/prettier-vscode#202]
Greetings,

I am using Solus https://solus-project.com/ and unfortunately, their build process for VSCode is currently blocked due to NPM5 and thus their repo version is stuck on 1.14 branch. 

In the meantime, I unpacked and installed VSCode through official site via .tar.gz. Problem is, seems like prettier does not work whatsoever. It used to work when VSCode was installed through repos but now that it is unpacked in my home directory prettier does nothing. 

Is there any way to make prettier work again?

**Comment by Nikki1993** [comment]
Here is dev console output 

```
mainThreadExtensionService.ts:117Activating extension `esbenp.prettier-vscode` failed: Cannot find module 'read-pkg-up'.
t.$localShowMessage @ mainThreadExtensionService.ts:117
17extensionHost.ts:335[Extension Host] Error: TextEditor disposed
    at t.$trySetDecorations (file:///home/nikki/Apps/vscode/resources/app/out/vs/workbench/workbench.main.js:28:3140811)
    at t.e.handle (file:///home/nikki/Apps/vscode/resources/app/out/vs/workbench/workbench.main.js:28:3100447)
    at s (file:///home/nikki/Apps/vscode/resources/app/out/vs/workbench/workbench.main.js:28:1029376)
    at f (file:///home/nikki/Apps/vscode/resources/app/out/vs/workbench/workbench.main.js:28:1030031)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Nikki1993** [comment]
Abort the mission, for some reason after reinstalling extension 3 times it worked oO I have no idea what went wrong.

**Comment by CiGit** [comment]
Great it finally went through.
You have no access to the marketplace? Nor "Install from VSIX..." ?

**Comment by Nikki1993** [comment]
I do, that's from where I got it.

**Comment by CiGit** [comment]
Seems to link with other installation troubles we had in the past #118
