### ISSUE TITLE
Prettier missing from list of formatters in "Format Document With..."

### ISSUE THREAD

**Issue by joshuous** [prettier/prettier-vscode#2028]
### Summary

Prettier no longer appears in the "Format Document With..." list of formatters.

### Github Repository to Reproduce Issue

https://github.com/prettier/prettier

### Steps To Reproduce:

1.  Install Prettier VSCode plugin
2. Clone the above prettier repo
3. Open the project with VSCode
4. Install dependencies
5. Open a JavaScript file in the project
5. Show all commands (cmd+shift+P) -> "Format Document With..."
6. Prettier is missing from the list of formatters

### Expected result

Prettier should appear as an option in the list of formatters.

### Actual result

Prettier is missing from the list of formatters. It is also not showing in the "Developer: Show Running Extensions" page.

### Additional information

Prettier was showing as an option before the 8.0.0 update.

**VS Code Version**:  1.57.1 and 1.58.0-insider

**Prettier Extension Version**: 8.0.0

**OS and version**: MacOS 10.15.7

## Prettier Log Output

Unfortunately, the Prettier button is also missing from the bottom toolbar.

**Comment by ridem** [comment]
Same issue here with prettier 8.0.0. In my case this is due to the extension not loading at all.

VS Code Version: 1.57.
Prettier Extension Version: 8.0.0
OS and version: MacOS 11.4

Setup:
- Multi-root workspace, trusted.
- prettier installed at the root of the workspace

Full trace:
```
[2021-06-22 16:47:41.147] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-22 16:47:41.147] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- ~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.2392 (~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:72632)
	at r (~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:72851)
	at Object.9854 (~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:1392)
	at r (~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:72851)
	at ~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:73022
	at ~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:74003
	at Object.<anonymous> (~/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:74024)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
	at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at m._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25973)
	at m._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12617)
	at m._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11676)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
 ```

**Comment by ntotten** [comment]
#2029
