### ISSUE TITLE
Prettier fails with error when it encounters Typescript override modifier

### ISSUE THREAD

**Issue by VEASTARK** [prettier/prettier-vscode#2032]
Example:
```javascript
class Greeter {
    greet(): void {
        console.log("Hi")
    }
}

class Greeter2 extends Greeter {
    override greet(): void {
        console.log("Hello there")
    }
}
```

Error:
```
["ERROR" - 5:25:01 PM] Error formatting document.
["ERROR" - 5:25:01 PM] ';' expected. (8:14)
   6 |
   7 | class Greeter2 extends Greeter {
>  8 |     override greet() : void {
     |              ^
   9 |         console.log("Hello there")
  10 |     }
  11 | }
SyntaxError: ';' expected. (8:14)
   6 |
   7 | class Greeter2 extends Greeter {
>  8 |     override greet() : void {
     |              ^
   9 |         console.log("Hello there")
  10 |     }
  11 | }
	at e (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/parser-typescript.js:1:384)
	at /home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/parser-typescript.js:1:3179433
	at Object.parse (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/parser-typescript.js:1:3179466)
	at Object.parse$a [as parse] (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/index.js:14892:19)
	at coreFormat (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/index.js:16425:16)
	at formatWithCursor$1 (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/index.js:16665:14)
	at /home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/index.js:60922:12
	at Object.format (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/node_modules/prettier/index.js:60942:12)
	at t.default.<anonymous> (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/dist/extension.js:1:16819)
	at Generator.next (<anonymous>)
	at s (/home/veastark/.vscode/extensions/esbenp.prettier-vscode-7.1.1/dist/extension.js:1:9119)
```

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by ntotten** [comment]
Upgrade to the 8.0.1 which has the latest prettier to support typescript 4.3 or install the latest prettier directly into your project.
