### ISSUE TITLE
Prettier doesn't recognize optional chaining syntax in TypeScript.

### ISSUE THREAD

**Issue by theJsTsGuy** [prettier/prettier-vscode#2332]
### Summary

Prettier was not able to format Typescript React files for 2-3 days. Today, I tried to dig deeper and found this on logs:

```
["INFO" - 8:43:21 AM] Formatting file:///d%3A/fiverr/paddylddy/video-quiz-widget/src/components/intro.tsx
["INFO" - 8:43:21 AM] Using ignore file (if present) at d:\fiverr\paddylddy\video-quiz-widget\.prettierignore
["INFO" - 8:43:21 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:43:21 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 8:43:21 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\fiverr\\paddylddy\\video-quiz-widget\\src\\components\\intro.tsx",
  "parser": "typescript"
}
["ERROR" - 8:43:21 AM] Error formatting document.
["ERROR" - 8:43:21 AM] Expression expected. (13:21)
  11 |         <video
  12 |           autoPlay
> 13 |           key={quiz?.questions?.[0]?.video}
     |                     ^
  14 |           muted={true}
  15 |           loop
  16 |           playsInline
SyntaxError: Expression expected. (13:21)
  11 |         <video
  12 |           autoPlay
> 13 |           key={quiz?.questions?.[0]?.video}
     |                     ^
  14 |           muted={true}
  15 |           loop
  16 |           playsInline
    at e (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:10629:19)
    at coreFormat (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:13846:23)
    at format (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14105:73)
    at formatWithCursor (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14121:12)
    at d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42389:15
    at Object.Success [as format] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42408:12)
    at t.default.<anonymous> (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\src\PrettierEditService.ts:434:45)
    at Generator.next (<anonymous>)
    at s (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\dist\extension.js:1:7872)
["INFO" - 8:43:21 AM] Formatting completed in 0.024ms.
```

### Github Repository to Reproduce Issue

It is a pure default extension, no config, no additional prettier or ESlint things.

### Steps To Reproduce:

1. Create a new tsx file
2. Add this content in it:
```tsx
import React from "react"

export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))

export const App = ( ) => {
    return <div className  =   "asdas">asdasdas</div>
}
```
3. Format file using command palette.

### Expected result

This should format the file correctly as there is no syntax error.

### Actual result
This is what logs say:
```
["INFO" - 8:50:15 AM] Formatting file:///d%3A/fiverr/paddylddy/video-quiz-widget/src/bug.tsx
["INFO" - 8:50:15 AM] Using ignore file (if present) at d:\fiverr\paddylddy\video-quiz-widget\.prettierignore
["INFO" - 8:50:15 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:50:15 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 8:50:15 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\fiverr\\paddylddy\\video-quiz-widget\\src\\bug.tsx",
  "parser": "typescript"
}
["ERROR" - 8:50:15 AM] Error formatting document.
["ERROR" - 8:50:15 AM] Expression expected. (3:69)
  1 | import React from "react"
  2 | 
> 3 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
  4 | 
  5 | export const App = ( ) => {
  6 |     return <div className  =   "asdas">asdasdas</div>
SyntaxError: Expression expected. (3:69)
  1 | import React from "react"
  2 | 
> 3 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
  4 | 
  5 | export const App = ( ) => {
  6 |     return <div className  =   "asdas">asdasdas</div>
    at e (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:10629:19)
    at coreFormat (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:13846:23)
    at format (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14105:73)
    at formatWithCursor (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14121:12)
    at d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42389:15
    at Object.Success [as format] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42408:12)
    at t.default.<anonymous> (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\src\PrettierEditService.ts:434:45)
    at Generator.next (<anonymous>)
    at s (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\dist\extension.js:1:7872)
["INFO" - 8:50:15 AM] Formatting completed in 0.046ms.
```

**VS Code Version**:
1.64.0-insider

**Prettier Extension Version**:
I think the latest one because reinstalling didn't fix this problem either. [9.0.0]

**OS and version**:
Windows 10 Pro 64-bit operating system

## Prettier Log Output

```
["INFO" - 8:48:56 AM] Formatting file:///d%3A/fiverr/paddylddy/video-quiz-widget/src/bug.tsx
["INFO" - 8:48:56 AM] Using ignore file (if present) at d:\fiverr\paddylddy\video-quiz-widget\.prettierignore
["INFO" - 8:48:56 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:48:56 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 8:48:56 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\fiverr\\paddylddy\\video-quiz-widget\\src\\bug.tsx",
  "parser": "typescript"
}
["ERROR" - 8:48:56 AM] Error formatting document.
["ERROR" - 8:48:56 AM] Expression expected. (1:55)
> 1 | export const s = () => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                       ^
SyntaxError: Expression expected. (1:55)
> 1 | export const s = () => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                       ^
    at e (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:10629:19)
    at coreFormat (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:13846:23)
    at format (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14105:73)
    at formatWithCursor (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14121:12)
    at d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42389:15
    at Object.Success [as format] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42408:12)
    at t.default.<anonymous> (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\src\PrettierEditService.ts:434:45)
    at Generator.next (<anonymous>)
    at s (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\dist\extension.js:1:7872)
["INFO" - 8:48:56 AM] Formatting completed in 0.045ms.
["INFO" - 8:49:13 AM] Formatting file:///d%3A/fiverr/paddylddy/video-quiz-widget/src/bug.tsx
["INFO" - 8:49:13 AM] Using ignore file (if present) at d:\fiverr\paddylddy\video-quiz-widget\.prettierignore
["INFO" - 8:49:13 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:49:13 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 8:49:13 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\fiverr\\paddylddy\\video-quiz-widget\\src\\bug.tsx",
  "parser": "typescript"
}
["ERROR" - 8:49:13 AM] Error formatting document.
["ERROR" - 8:49:13 AM] Expression expected. (1:69)
> 1 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
SyntaxError: Expression expected. (1:69)
> 1 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
    at e (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:10629:19)
    at coreFormat (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:13846:23)
    at format (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14105:73)
    at formatWithCursor (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14121:12)
    at d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42389:15
    at Object.Success [as format] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42408:12)
    at t.default.<anonymous> (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\src\PrettierEditService.ts:434:45)
    at Generator.next (<anonymous>)
    at s (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\dist\extension.js:1:7872)
["INFO" - 8:49:13 AM] Formatting completed in 0.019ms.
["INFO" - 8:50:15 AM] Formatting file:///d%3A/fiverr/paddylddy/video-quiz-widget/src/bug.tsx
["INFO" - 8:50:15 AM] Using ignore file (if present) at d:\fiverr\paddylddy\video-quiz-widget\.prettierignore
["INFO" - 8:50:15 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:50:15 AM] No local configuration (i.e. .prettierrc or .editorconfig) detected, falling back to VS Code configuration
["INFO" - 8:50:15 AM] Prettier Options:
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\fiverr\\paddylddy\\video-quiz-widget\\src\\bug.tsx",
  "parser": "typescript"
}
["ERROR" - 8:50:15 AM] Error formatting document.
["ERROR" - 8:50:15 AM] Expression expected. (3:69)
  1 | import React from "react"
  2 | 
> 3 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
  4 | 
  5 | export const App = ( ) => {
  6 |     return <div className  =   "asdas">asdasdas</div>
SyntaxError: Expression expected. (3:69)
  1 | import React from "react"
  2 | 
> 3 | export          const s = (     ) => console.log(            window?.localStorage?.setItem("dsd", "Sdsd"))
    |                                                                     ^
  4 | 
  5 | export const App = ( ) => {
  6 |     return <div className  =   "asdas">asdasdas</div>
    at e (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:329)
    at Object.parse (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\parser-typescript.js:1:2172609)
    at Object.parse$2 [as parse] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:10629:19)
    at coreFormat (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:13846:23)
    at format (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14105:73)
    at formatWithCursor (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:14121:12)
    at d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42389:15
    at Object.Success [as format] (d:\fiverr\paddylddy\video-quiz-widget\node_modules\prettier\index.js:42408:12)
    at t.default.<anonymous> (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\src\PrettierEditService.ts:434:45)
    at Generator.next (<anonymous>)
    at s (c:\Users\M.Omar\.vscode-insiders\extensions\esbenp.prettier-vscode-9.0.0\dist\extension.js:1:7872)
["INFO" - 8:50:15 AM] Formatting completed in 0.046ms.
```

**Comment by theJsTsGuy** [comment]
Same output when using vscode stable.

**Comment by ntotten** [comment]
This is usually because you aren't using the right version of Typescript. Can you verify you are on the latest version of typescript?
