### ISSUE TITLE
prettierrc is not working in my VS Code (despite using the same for 'format on save')

### ISSUE THREAD

**Issue by sambit089** [prettier/prettier-vscode#2434]
Hi All,

Although I am using the option "editor.defaultFormatter": "esbenp.prettier-vscode" and "format on Save" in my VS Code, I am still unable to format my code.

**Comment by ntotten** [comment]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information.

**Comment by sambit089** [comment]
Hi, Thanks for the response.
I am bit new to VS Code. Not sure what I am missing. However, just pasting the Error information that I am getting while clicking on "Prettier" icon on right bottom: (hope that helps)

Error: Cannot find module 'prettier' from '/Users/sambitnayak/Desktop/Learn Aura'
	at Function.e.exports [as sync] (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:43665)
	at t.ModuleResolver.findPkg (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:5790)
	at t.ModuleResolver.<anonymous> (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:3671)
	at Generator.next (<anonymous>)
	at /Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:2894
	at new Promise (<anonymous>)
	at n (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:2639)
	at t.ModuleResolver.getPrettierInstance (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:3403)
	at t.default.<anonymous> (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:8998)
	at Generator.next (<anonymous>)
	at /Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:7201
	at new Promise (<anonymous>)
	at n (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:6946)
	at handleActiveTextEditorChanged (/Users/sambitnayak/.vscode/extensions/esbenp.prettier-vscode-8.1.0/dist/extension.js:1:8664)
	at d.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
	at /private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:56700
	at d.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
	at b.acceptDocumentsAndEditorsDelta (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:161009)
	at b.$acceptDocumentsAndEditorsDelta (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:159110)
	at c._doInvokeHandler (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12743)
	at c._invokeHandler (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12435)
	at c._receiveRequest (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11097)
	at c._receiveOneMessage (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9900)
	at /private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8004
	at d.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
	at h.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
	at /private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29836
	at d.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
	at h.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
	at r._receiveMessage (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)
	at /private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921
	at d.fire (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
	at u.acceptChunk (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)
	at /private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486
	at Socket._ (/private/var/folders/j3/ycgqq1x92vlc_flz62q19kg40000gn/T/AppTranslocation/13DC367A-A24D-4401-A27B-3ED90564B7E9/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13107)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by sambit089** [comment]
Hi,
Why did you close this issue?
It's still unresolved.

Please let me know.
