### ISSUE TITLE
why I use "import type" tell me SyntaxError?

### ISSUE THREAD

**Issue by huihuilovekuikui** [prettier/prettier-vscode#2563]
### Summary
 I use "import type" tell me SyntaxError

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

keyboad formatting

### Expected result

finish right formatting

### Actual result
error

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:1.66.2

**Prettier Extension Version**:Prettier - Code formatter v9.5.0

**OS and version**:macos 12.3.1

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```
["INFO" - 11:32:18] Formatting file:///Users/tihuiwu/hui_workspace/admin/src/pages/course/components/Classify/InputTable.tsx
["INFO" - 11:32:18] Using config file at '/Users/tihuiwu/hui_workspace/admin/.prettierrc.js'
["INFO" - 11:32:18] Using ignore file (if present) at /Users/tihuiwu/hui_workspace/admin/.prettierignore
["INFO" - 11:32:18] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 11:32:18] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:32:18] Prettier Options:
{
  "filepath": "/Users/tihuiwu/hui_workspace/admin/src/pages/course/components/Classify/InputTable.tsx",
  "parser": "typescript",
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "quoteProps": "as-needed",
  "jsxSingleQuote": false,
  "trailingComma": "none",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "always",
  "rangeStart": 0,
  "rangeEnd": null,
  "requirePragma": false,
  "insertPragma": false,
  "proseWrap": "preserve",
  "htmlWhitespaceSensitivity": "css",
  "endOfLine": "lf"
}
["ERROR" - 11:32:18] Error formatting document.
["ERROR" - 11:32:18] '=' expected. (1:13)
> 1 | import type { InputRef } from 'antd';
    |             ^
  2 | import type { FormInstance } from 'antd/lib/form'; 
  3 | 
  4 | import React, { useContext, useState, useEffect, useRef } from 'react';
SyntaxError: '=' expected. (1:13)
> 1 | import type { InputRef } from 'antd';
    |             ^
  2 | import type { FormInstance } from 'antd/lib/form'; 
  3 | 
  4 | import React, { useContext, useState, useEffect, useRef } from 'react';
    at t (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/parser-typescript.js:1:347)
    at Object.parse (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:13252:23)
    at format (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:13526:12)
    at /Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:44207:15
    at Object.Success [as format] (/Users/tihuiwu/hui_workspace/admin/node_modules/prettier/index.js:44226:12)
    at t.default.format (/Users/tihuiwu/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:463:45)
    at t.PrettierEditProvider.provideEdits (/Users/tihuiwu/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:322:22)
    at B.provideDocumentFormattingEdits (/private/var/folders/vw/3h0rxs0s4p9d9crrpmrm3gfh0000gn/T/AppTranslocation/08C19F49-17EE-465D-BF5C-2AB58795509E/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:102917)
["INFO" - 11:32:18] Formatting completed in 0.016ms.

**Comment by ntotten** [comment]
You need to use the right version of prettier with the right version of typescript. This plugin doesn't use the typescript module at all, but older versions of prettier don't support new features of the typescript language.
