### ISSUE TITLE
Formatting with a local module reference fails with `Error: Cannot find module '...'`

### ISSUE THREAD

**Issue by nickmccurdy** [prettier/prettier-vscode#2599]
### Summary

Formatting with a local module reference fails with `Error: Cannot find module '...'`

I would need this to test [my config](https://github.com/nickmccurdy/prettier-config) locally. As a workaround, I install the package globally, which makes testing more difficult. This could also be a use case for complex projects that need to change Prettier configs without publishing them to packages.

### Github Repository to Reproduce Issue

https://github.com/nickmccurdy/prettier-config/tree/configure-prettier-locally

### Steps To Reproduce:

1. Install VSCode and Prettier VSCode
2. Install [my config](https://github.com/nickmccurdy/prettier-config) locally (alternatively you can use any Prettier config package with `"prettier": "."` in `package.json`)
```sh
git clone --branch configure-prettier-locally https://github.com/nickmccurdy/prettier-config
cd prettier-config
npm install
code .
```
3. Run `Format Document` with Prettier

### Expected result

The file should be formatted, as if I was using `prettier --write`

### Actual result

The file is not formatted, and an error is logged to the extension's output

### Additional information

**VS Code Version**:

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

**Prettier Extension Version**: 9.5.0

**OS and version**: macOS 12.4

## Prettier Log Output

```
["INFO" - 4:04:35 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 4:04:35 AM] Extension Version: 9.5.0.
["INFO" - 4:04:39 AM] Formatting file:///Users/nick/Repos/prettier-config/package.json
["ERROR" - 4:04:39 AM] Error resolving prettier configuration for /Users/nick/Repos/prettier-config/package.json
["ERROR" - 4:04:39 AM] Cannot find module '.'
Require stack:
- /Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/index.js
- /Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Error: Cannot find module '.'
Require stack:
- /Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/index.js
- /Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at _.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:761)
    at Object.transform (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/index.js:18233:34)
    at run (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/third-party.js:8418:53)
    at Explorer.search (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/third-party.js:8407:24)
    at Object.loggingService [as resolveConfigFile] (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/index.js:18307:22)
    at t.ModuleResolver.resolvedConfig [as getResolvedConfig] (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/ModuleResolver.ts:220:12)
    at t.default.format (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:378:9)
    at t.PrettierEditProvider.provideEdits (/Users/nick/.vscode/extensions/esbenp.prettier-vscode-9.5.0/src/PrettierEditService.ts:322:22)
    at M.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:137239)
```

**Comment by nickmccurdy** [comment]
This appears to be an issue in Prettier, as it actually ignores my config completely.
