### ISSUE TITLE
Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by db-007** [prettier/prettier-vscode#269]
My VSCode settings.json:
```
  "editor.snippetSuggestions": "top",
  "prettier.eslintIntegration": true,
  "editor.formatOnSave": true
```

My .eslintrc.json:
```
{
    "extends": "airbnb",
    "parser": "babel-eslint",
    "env": {
      "browser": true
    },
    "plugins": [
      "react"
    ],
    "rules": {
      "react/jsx-filename-extension": [
        2,
        {
          "extensions": [
            ".js",
            ".jsx"
          ]
        }
      ],
      "react/forbid-prop-types": [
        0
      ],
      "react/require-default-props": [
        0
      ],
      "global-require": [
        0
      ]
    }
  }
```

My package.json:
```
{
  "name": "CurrencyCoverter",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.5.1",
    "jest-expo": "^22.0.0",
    "prettier": "^1.8.2",
    "prettier-eslint": "^6.2.0",
    "react-native-scripts": "1.7.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "lint": "eslint app/",
    "lint:fix": "eslint app/ --fix"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^22.0.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5"
  }
}
```

Running lint returns:

```
dinob@dbmac:~/dummy/CurrencyCoverter $ npm run lint

> CurrencyCoverter@0.1.0 lint /Users/dinob/dummy/CurrencyCoverter
> eslint app/

/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint-config-airbnb-base/rules/es6.js:
	Configuration for rule "prefer-destructuring" is invalid:
	Value "data["0"].VariableDeclarator" has additional properties.
	Value "data["0"].AssignmentExpression" has additional properties.

Referenced from: /Users/dinob/dummy/CurrencyCoverter/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/dinob/dummy/CurrencyCoverter/.eslintrc.json
Error: /Users/dinob/dummy/CurrencyCoverter/node_modules/eslint-config-airbnb-base/rules/es6.js:
	Configuration for rule "prefer-destructuring" is invalid:
	Value "data["0"].VariableDeclarator" has additional properties.
	Value "data["0"].AssignmentExpression" has additional properties.

Referenced from: /Users/dinob/dummy/CurrencyCoverter/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/dinob/dummy/CurrencyCoverter/.eslintrc.json
    at validateRuleOptions (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-file.js:559:19)
    at configExtends.reduceRight (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-file.js:408:28)
    at load (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-file.js:566:22)
    at configExtends.reduceRight (/Users/dinob/dummy/CurrencyCoverter/node_modules/eslint/lib/config/config-file.js:424:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! CurrencyCoverter@0.1.0 lint: `eslint app/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the CurrencyCoverter@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by CiGit** [comment]
I don't get it. This seems to be an error on your npm scripts.
What with this extension?

**Comment by hardchor** [comment]
I'm getting the same error message, but unrelated to any npm scripts (running formatonsave with	eslint integration):


```json
    "editor.formatOnSave": true,
    "prettier.eslintIntegration": true
```

**Comment by nirajbisht** [comment]
Unable to connect to the database: TypeError: Cannot read property 'sync' of undefined
 can anyone help me come out of  this ...?
