### ISSUE TITLE
Prettier fails with error when it encounters Typescript override modifier

### ISSUE THREAD

**Issue by puranjayjain** [prettier/prettier-vscode#2803]
### Summary
Override keyword results in an error in typescript based formating.

### Expected result
Formatting should happen

### Actual File
Example:

```typescript

/**
 * Anchor button base.
 */
@Directive()
export class AnchorBase extends ButtonBase implements OnInit, OnDestroy {
  disabled = false;
  tabIndex?: number;

  constructor(elementRef: ElementRef, platform: Platform, ngZone: NgZone, focusMonitor: FocusMonitor) {
    super(elementRef, platform, ngZone, focusMonitor);
  }

  /**
   * The function runs outside of the Angular zone, and adds a click event listener to the element that
   * the directive is attached to
   */
  ngOnInit(): void {
    this._ngZone.runOutsideAngular(() => {
      this.elementRef.nativeElement.addEventListener('click', this._haltDisabledEvents);
    });
  }

  /**
   * It removes the event listener from the element.
   */
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.elementRef.nativeElement.removeEventListener('click', this._haltDisabledEvents);
  }

  _haltDisabledEvents = (event: Event): void => {
    // A disabled button shouldn't apply any actions
    if (this.disabled) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  };
}

```

## Prettier Log Output
```bash
["INFO" - 12:48:37 PM] Prettier Options:
{
  "filepath": "~/src/button/button-base.ts",
  "parser": "typescript",
  "singleQuote": true,
  "printWidth": 120
}
["ERROR" - 12:48:37 PM] Error formatting document.
["ERROR" - 12:48:37 PM] ';' expected. (121:12)
  119 |    * It removes the event listener from the element.
  120 |    */
> 121 |   override ngOnDestroy(): void {
      |            ^
  122 |     super.ngOnDestroy();
  123 |     this.elementRef.nativeElement.removeEventListener('click', this._haltDisabledEvents);
  124 |   }
SyntaxError: ';' expected. (121:12)
  119 |    * It removes the event listener from the element.
  120 |    */
> 121 |   override ngOnDestroy(): void {
      |            ^
  122 |     super.ngOnDestroy();
  123 |     this.elementRef.nativeElement.removeEventListener('click', this._haltDisabledEvents);
  124 |   }
  <hiding irrelevant file path errors> 
    at t.default.format (/Users/puranjayjain/.vscode/extensions/esbenp.prettier-vscode-9.10.3/dist/extension.js:1:14731)
    at t.PrettierEditProvider.provideEdits (/Users/puranjayjain/.vscode/extensions/esbenp.prettier-vscode-9.10.3/dist/extension.js:1:11417)
    at B.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:45902)
["INFO" - 12:48:37 PM] Formatting completed in 7ms.
```

### Additional information

**VS Code Version**:
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:22:48.959Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Prettier Extension Version**:
Extension Version: 9.10.3.

**OS and version**:
OS: Macos ventura `13.0.1 (22A400)`

**Comment by puranjayjain** [comment]
Related https://github.com/prettier/prettier-vscode/issues/2032

**Comment by ntotten** [comment]
**Recommendation**: Upgrade to the latest version of prettier.

**Explanation**: You are likely using a newer version of Typescript than the version of prettier you have installed supports. Typescript features are added in new prettier releases. See the prettier blog to learn more about what features of typescript are enabled for each version of prettier: https://prettier.io/blog/
