### ISSUE TITLE
Different output between terminal and Vs-Code extension

### ISSUE THREAD

**Issue by Alfystar** [prettier/prettier-vscode#2898]
### Summary

Hello everyone,
I ran into a rather strange bug these days.

I noticed that, if I try to use the program on a badly formatted (.cls) Apex class (on purpose), the output log differs if I call the program from the terminal or from a plugin integrated in VS-code

### Steps To Reproduce:

1.  Create an apex class (with something wrong, for example, one ";" missing")
1.  Run prettier from terminal
1.  Run prettier from Vs-Code

### Expected result
Terminal result:
```
└─▶ $ prettier src/main/default/classes/ITA_IFM_Results_Test.cls
src\main\default\classes\ITA_IFM_Results_Test.cls[error] src\main\default\classes\ITA_IFM_Results_Test.cls: Error: Missing ';' at 'Account'. Syntax(error = MissingSyntax(loc = (16, 9, 45, 52), actual = 'Account', expected = ;))
[error]     at Object.parse (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier-plugin-apex\src\parser.js:512:13)
[error]     at Object.parse (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\index.js:7334:23)
[error]     at coreFormat (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\index.js:8645:18)
[error]     at formatWithCursor2 (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\index.js:8837:18)
[error]     at Object.formatWithCursor (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\index.js:37229:12)
[error]     at format (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\cli.js:14748:24)
[error]     at formatFiles2 (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\cli.js:14860:22)
[error]     at async main (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\cli.js:15077:5)
[error]     at async Object.run (C:\Users\A409806\AppData\Roaming\npm\node_modules\prettier\cli.js:15024:5)
```

### Actual result
And this is the plugin ouptut
```
["INFO" - 4:05:19 PM] Formatting file:///c%3A/Users/A409806/Documents/Salesforce/CMRT_Italia/src/main/default/classes/ITA_IFM_Results_Test.cls
["INFO" - 4:05:19 PM] Using config file at 'c:\Users\A409806\Documents\Salesforce\CMRT_Italia\.prettierrc'
["DEBUG" - 4:05:19 PM] Local prettier module path: 'c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js'
["INFO" - 4:05:19 PM] Using ignore file (if present) at c:\Users\A409806\Documents\Salesforce\CMRT_Italia\.prettierignore
["INFO" - 4:05:19 PM] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 4:05:19 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 4:05:19 PM] Prettier Options:
{
  "filepath": "c:\\Users\\A409806\\Documents\\Salesforce\\CMRT_Italia\\src\\main\\default\\classes\\ITA_IFM_Results_Test.cls",
  "parser": "apex",
  "printWidth": 350,
  "tabWidth": 4,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": false,
  "loglevel": "log"
}
["ERROR" - 4:05:20 PM] Error formatting document.
["ERROR" - 4:05:20 PM] Missing ';' at 'Account'.
Error: Missing ';' at 'Account'.
    at Object.parse (c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier-plugin-apex\dist\src\parser.js:479:19)
    at Object.parse (c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js:7515:23)
    at coreFormat (c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js:8829:18)
    at formatWithCursor2 (c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js:9021:18)
    at c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js:38176:12
    at Object.format (c:\Users\A409806\Documents\Salesforce\CMRT_Italia\node_modules\prettier\index.js:38190:12)
    at t.default.format (c:\Users\A409806\.vscode\extensions\esbenp.prettier-vscode-9.10.4\dist\extension.js:1:14731)
    at t.PrettierEditProvider.provideEdits (c:\Users\A409806\.vscode\extensions\esbenp.prettier-vscode-9.10.4\dist\extension.js:1:11417)
    at q.provideDocumentFormattingEdits (c:\Users\A409806\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:39883)
["INFO" - 4:05:20 PM] Formatting completed in 719ms.
```

### Additional information

The data missing, in plugin log, is:
`Syntax(error = MissingSyntax(loc = (16, 9, 45, 52), actual = 'Account', expected = ;))`

**VS Code Version**:

Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Prettier Extension Version**: 2.7.1

**OS and version**: Windows 11

**Comment by Alfystar** [comment]
Hi @ntotten, I'm here to explain, what are not clear?
