### ISSUE TITLE
Broken in vs code insiders

### ISSUE THREAD

**Issue by eldair** [prettier/prettier-vscode#3000]
### Summary

Prettier/extension is not loaded

### Steps To Reproduce:

1.  Start VS Code

### Actual result

Prettier doesn't work

**VS Code Version**:

Version: 1.79.0-insider (user setup)
Commit: f5d658848a7d39546e48b9393690b5ff18473a7b
Date: 2023-05-04T05:21:45.650Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Prettier Extension Version**: 9.12.0

**OS and version**: ubuntu 22.04 wsl2 on win 11

## Prettier Log Output

```
["INFO" - 5:52:19 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 5:52:19 PM] Extension Version: 9.12.0.
["INFO" - 5:52:19 PM] Attempted to determine module path from package.json
["ERROR" - 5:52:19 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 5:52:19 PM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/eldair/.vscode-server-insiders/bin/f5d658848a7d39546e48b9393690b5ff18473a7b/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:35702)
	at b (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37533)
	at /home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37158
	at Function.e.exports [as sync] (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37204)
	at t.ModuleResolver.findPkg (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:9781)
	at t.default.handleActiveTextEditorChangedSync (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:9383)
	at t.default.registerDisposables (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:12226)
	at /home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:77800
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by eldair** [comment]
I tested other formatters and they're working fine.

**Comment by joaodfmota** [comment]
In my case, it seems like a problem with `resolver`. The extension is not working only in Monorepo.

`dist/extensions.js:1:37517`

From:
```
var l=e+I[a]
```
To:
```
var l=e+'/index'+I[a]
```

**Comment by eldair** [comment]
@joaodfmota yes, this does work!

**Comment by WookashWackomy** [comment]
Just had the same issue with a monorepo setup and what @joaodfmota wrote did help indeed.

**Comment by JonrGull** [comment]
The most recent update seems to have fixed this issue, at least for me.

**Comment by eldair** [comment]
@ntotten sorry for tagging you, do you maybe have an idea where would the error be?

**Comment by shivamlync** [comment]
```
["ERROR" - 11:12:50 AM] Prettier could not be loaded. See previous logs for more information.
["INFO" - 11:13:52 AM] Formatting file:///media/shivam/7fe1e626-a4c2-494c-826e-c326612ee89c/lync/npmpackages/m/webpack.config.js
["INFO" - 11:13:52 AM] Attempted to determine module path from package.json
["ERROR" - 11:13:52 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 11:13:52 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/shivam/.vscode-server-insiders/bin/d0ca6131bfe1936153df2f8a11f85e3790ec1f4b/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:35702)
	at b (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37533)
	at /home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37158
	at Function.e.exports [as sync] (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:37204)
	at t.ModuleResolver.findPkg (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:7499)
	at t.ModuleResolver.getPrettierInstance (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:3251)
	at t.default.format (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:13495)
	at async t.PrettierEditProvider.provideEdits (/home/shivam/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:11367)
	at async B.provideDocumentFormattingEdits (/home/shivam/.vscode-server-insiders/bin/d0ca6131bfe1936153df2f8a11f85e3790ec1f4b/out/vs/workbench/api/node/extensionHostProcess.js:102:49019)
["ERROR" - 11:13:52 AM] Prettier could not be loaded. See previous logs for more information.

```

**Comment by Dnouv** [comment]
Well, not sure if it is the correct way to resolve but,

After changing the prettier path settings to the ones below, it does the trick.
`"prettier.prettierPath": "./node_modules/prettier"`

Thank you!

**Comment by gmotyl** [comment]
thank you @Dnouv , this helped me as well:

> After changing the prettier path settings to the ones below, it does the trick. `"prettier.prettierPath": "./node_modules/prettier"`

**Comment by pikilon** [comment]
THank you @Dnouv this saved my day
> Well, not sure if it is the correct way to resolve but,
> 
> After changing the prettier path settings to the ones below, it does the trick. `"prettier.prettierPath": "./node_modules/prettier"`
> 
> Thank you!

**Comment by firxworx** [comment]
+1 thanks @Dnouv, your solution worked for me. Previously I had no issues in the non-Insiders VSCode in the same codebase.

To add keywords for those searching this out: I'm sure a lot of people are trying Insiders because of the GitHub Copilot Chat and wondering why prettier is broken. 

In case it helps those troubleshooting I'll add how to see Prettier log output: 

- ensure the Terminal view is open (<kbd>Ctrl/⌘</kbd> + <kbd>`</kbd>)
- open the "OUTPUT" tab and choose "Prettier" from the select/drop-down element

You'll see any error or success output here when you try to format a file with prettier.

**Comment by rpturbina** [comment]
@Dnouv i have some issues and your helpful solution worked for me! Thanks

**Comment by forrcaho** [comment]
It's nice that there _is_ a workaround, but I was hoping this issue would be fixed. I switched from Insiders to the standard VSCode release when this started happening, and now the standard VSCode has just started to have the same error.

Now I'll have to apply the workaround, and every indication here makes me think it will work fine. But I think it's important to note that this is still an error that should be fixed.

**Comment by codeninja** [comment]
@Dnouv you're amazing. Thank you!

**Comment by bestis** [comment]
> It's nice that there _is_ a workaround, but I was hoping this issue would be fixed.

Me too! At least the workaround make it work, but then it's not reading .prettierrc and doing what that says and that's not nice either.

**Comment by 205g0** [comment]
Seems still to be broken in nromal VS Code
