### ISSUE TITLE
Not working at all "no such file or directory, uv_cwd"

### ISSUE THREAD

**Issue by eldair** [prettier/prettier-vscode#3006]
### Summary

Prettier/extension is not loaded

### Steps To Reproduce:

1.  Start VS Code

### Actual result

Prettier doesn't work

**VS Code Version**:

Version: 1.79.0-insider (user setup)
Commit: f1258a5fbed44b8f84a097c73c1799c13c5c3646
Date: 2023-05-17T05:27:38.052Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Prettier Extension Version**: 9.12.0

**OS and version**: ubuntu 22.04 wsl2 on win 11

## Prettier Log Output

```
["INFO" - 6:15:42 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 6:15:42 PM] Extension Version: 9.12.0.
["ERROR" - 6:15:42 PM] Error registering extension
["ERROR" - 6:15:42 PM] ENOENT: no such file or directory, uv_cwd
Error: ENOENT: no such file or directory, uv_cwd
	at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
	at process.cwd (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/node_modules/graceful-fs/polyfills.js:10:19)
	at process.cwd (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/extensions/npm/dist/npmMain.js:2:154055)
	at /home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/node_modules/prettier/index.js:38129:62
	at Array.flatMap (<anonymous>)
	at Object.load (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/node_modules/prettier/index.js:38128:60)
	at Object.load [as loadPlugins] (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/node_modules/prettier/index.js:16147:23)
	at Object.getSupportInfo (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/node_modules/prettier/index.js:38181:24)
	at t.default.getSelectors (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:10525)
	at t.default.registerGlobal (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:12339)
	at e.activate (/home/eldair/.vscode-server-insiders/extensions/esbenp.prettier-vscode-9.12.0/dist/extension.js:1:77501)
	at Function.fb (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:114:14750)
	at Function.eb (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:114:14453)
	at /home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:114:12476
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.n (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:98:6644)
	at async w.m (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:98:6607)
	at async w.l (/home/eldair/.vscode-server-insiders/bin/f1258a5fbed44b8f84a097c73c1799c13c5c3646/out/vs/workbench/api/node/extensionHostProcess.js:98:6064)
```

**Comment by eldair** [comment]
Probably an issue in vscode release, working now
