### ISSUE TITLE
Prettier pluguin doesn't work with vscode 1.79.0 - error "cannot read properties of undefined (reading 'uid')"

### ISSUE THREAD

**Issue by ZiiMakc** [prettier/prettier-vscode#3019]
### Summary

Prettier plugin doesn't work with vscode 1.79.0 (before update it worked fine)

### Steps To Reproduce:

Run format

### Expected result

Document should be formatted

### Actual result

Document not formatted, error shown in terminal prettier output

### Additional information

Repository is monorepo

### Versions:
- prettier: 2.8.8
- prettier vscode: 9.13.0
- vscode: 1.79.0
- windows 11 wsl

## Prettier Log Output

Error:
```
["ERROR" - 12:05:24 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 12:05:24 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/ziimakc/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.format (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:13495)
	at async t.PrettierEditProvider.provideEdits (/home/ziimakc/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:11367)
	at async U.provideDocumentFormattingEdits (/home/ziimakc/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:102:45790)
["ERROR" - 12:05:24 AM] Prettier could not be loaded. See previous logs for more information.
```

**Comment by ZiiMakc** [comment]
Related #3000

Quick fix, add to project settings in `.vscode/settings.json`

```
"prettier.prettierPath": "./node_modules/prettier"
``

**Comment by oncet** [comment]
Having the same problem. If the project I'm working on has `prettier` installed as a dependency, the plugin fails an throws the same error as OP.

**Comment by szszoke** [comment]
> Related #3000
> 
> Quick fix, add to project settings in `.vscode/settings.json`
> 
> ```
> "prettier.prettierPath": "./node_modules/prettier"
> ```

This does't work for me. I still get the same error.

I do have my project in a sub-directory, so I changed the path accordingly.

**Comment by luchillo17** [comment]
@szszoke Make sure you're changing `prettierPath` not `prettierConfigPath`, very similar names, I made that mistake a sec ago.

**Comment by szszoke** [comment]
> @szszoke Make sure you're changing `prettierPath` not `prettierConfigPath`, very similar names, I made that mistake a sec ago.

No worries! I just downgraded VS Code until this is resolved.

**Comment by szszoke** [comment]
> > > @szszoke Make sure you're changing `prettierPath` not `prettierConfigPath`, very similar names, I made that mistake a sec ago.
> > 
> > 
> > No worries! I just downgraded VS Code until this is resolved.
> 
> for me, it work, on vscode settings on workSpaces.
> 
> `{ "prettier.prettierPath": "./node_modules/prettier" }`

I tested again and it still doesn't work so I downgraded VS Code again.

**Comment by xylinq** [comment]
> vs code upgrade to 1.79.1

still have problem，not work

**Comment by luchillo17** [comment]
Tested with a recent update, seems to be working after removing the `prettierPath` workaround.

**Comment by sosukesuzuki** [comment]
@luchillo17 1.79.2?

**Comment by DylanSpOddball** [comment]
FWIW, I just tested with VSCode v1.79.2, this problem still occurred when not using the workaround.

**Comment by luchillo17** [comment]
Yes v1.79.2, just restarted my WSL2 instance to make sure it still worked, which version has #3030 in?

**Comment by moontai0724** [comment]
In my testing, I found that Pretter worked successfully on my local environment. However, when attempting to use it on my remote environment via remote-ssh, it will encountered errors.

---

| VSCode | Remote SSH | Prettier |
|--------|--------|--------|
| v1.19.2| v0.102.0| v9.13.0 |

When VSCode Started:
![image](https://github.com/prettier/prettier-vscode/assets/25532663/75773c71-f5bd-455c-989a-9ed887cbb2c8)

When Formatting Files:
![image](https://github.com/prettier/prettier-vscode/assets/25532663/81876370-7508-47bd-9a3a-ef32bdab0240)

<details><summary>Full Error Record</summary>
<p>

```
["INFO" - 9:22:31 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 9:22:31 AM] Extension Version: 9.13.0.
["INFO" - 9:22:39 AM] Attempted to determine module path from package.json
["ERROR" - 9:22:39 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 9:22:39 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9781)
	at handleActiveTextEditorChangedSync (/home/moontai0724/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9383)
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at /home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:104:17303
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at e.ExtHostDocumentsAndEditors.acceptDocumentsAndEditorsDelta (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:14003)
	at e.ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:12318)
	at s.N (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11717)
	at s.M (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11435)
	at s.H (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:10516)
	at s.G (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:9494)
	at /home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:8282
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at /home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:32461
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at D.E (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:18830)
	at /home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:16818
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at h.acceptChunk (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:12514)
	at /home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:11801
	at b.invoke (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at E.u (/home/moontai0724/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:20017)
```

</p>
</details> 

| VSCode  |           Remote SSH            | Prettier |
|:-------:|:-------------------------------:|:--------:|
| v1.19.2 | v0.103.2023061415 (pre-release) | v9.13.0  |

![image](https://github.com/prettier/prettier-vscode/assets/25532663/9d8ad087-255e-448f-aa81-b82d23a452e0)

**Comment by AhmedKhaliid** [comment]
prettier isn't working in my vscode and give me an error message in OUTPUT 
Error resolving prettier configuration
Error loading node module
note: changed Prettier Path {"prettier.prettierPath": "./node_modules/prettier"}
