### ISSUE TITLE
Not working on container

### ISSUE THREAD

**Issue by buracember** [prettier/prettier-vscode#3028]
Type: <b>Bug</b>

1 - attach vs code to a dev container
2 - press the prettier button on the right bottom corner 
3 -  see the output 
Attempted to determine module path from package.json
["ERROR" - 7:15:22 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 7:15:22 PM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9781)
	at handleActiveTextEditorChangedSync (/root/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9383)
	at b.invoke (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at /root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:104:17303
	at b.invoke (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at e.ExtHostDocumentsAndEditors.acceptDocumentsAndEditorsDelta (/root/.vscode-server/bin/4cb974a7aed77a74c7813bdccd99ee0d04901215/out/vs/workbench/api/node/extensionHostProcess.js:102:14003)

Extension version: 9.13.0
VS Code version: Code 1.79.1 (Universal) (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:16:49.215Z)
OS version: Darwin arm64 22.4.0
Modes:
Remote OS version: Linux arm64 5.10.104-linuxkit
Remote OS version: Linux arm64 5.10.104-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id c4ec0200-29f4-4e9a-8ab3-1e142d1aa518|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container test_test1 (test1) @ desktop-linux|
|OS|Linux arm64 5.10.104-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|7.65GB (1.41GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container test_test2 (test2) @ desktop-linux|
|OS|Linux arm64 5.10.104-linuxkit|
|CPUs|unknown (4 x 0)|
|Memory (System)|7.65GB (1.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showindicator:30766890
pythongtdpathcf:30739705
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by jaydiablo** [comment]
I believe this is the same issue as this one: #3019

**Comment by buracember** [comment]
Yes. Thanks!
