### ISSUE TITLE
Not working on WSL

### ISSUE THREAD

**Issue by thamys** [prettier/prettier-vscode#3031]
Type: <b>Bug</b>

Still happening

Extension version: 9.13.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (0.53GB free)|
|Process Argv|--crash-reporter-id cdfd3c02-64b4-4284-a8d4-3b799183dfff|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpath:30769146
dh2dc718:30763024
pythondjangots:30768919

```

</details>

**Comment by mclxly** [comment]
me too

`quickfix: at .vscode/settings.json add "prettier.prettierPath": "./node_modules/prettier" on settings { }`

this solution not works

**Comment by yn4v4s** [comment]
Can confirm this: Win 11 WSL2 VSCode 1.79.2_system

```
["INFO" - 4:19:07 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 4:19:07 PM] Extension Version: 9.13.0.
["INFO" - 4:19:07 PM] Attempted to determine module path from package.json
["ERROR" - 4:19:07 PM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 4:19:07 PM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/potter/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9781)
	at t.default.handleActiveTextEditorChangedSync (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9383)
	at t.default.registerDisposables (/home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:12226)
	at /home/potter/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:77896
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ntotten** [comment]
I am not able to reproduce this issue. A lot of the time these issues are caused by various version and config settings that are difficult to duplicate. Please provide a sample Github repo that I can use to duplicate this issue. For more details see [this guide](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo).

**Comment by dschoeni** [comment]
Same behavior as @yn4v4s reported here, simply stopped working:

```
["INFO" - 10:04:31 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:04:31 AM] Extension Version: 9.13.0.
["INFO" - 10:04:31 AM] Attempted to determine module path from package.json
["ERROR" - 10:04:31 AM] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 10:04:31 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/home/REDACTED/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
	at /home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36677
	at Function.e.exports [as sync] (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:36723)
	at t.ModuleResolver.findPkg (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:7297)
	at t.ModuleResolver.getPrettierInstance (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:3251)
	at t.default.handleActiveTextEditorChanged (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9781)
	at t.default.handleActiveTextEditorChangedSync (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:9383)
	at t.default.registerDisposables (/home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:12226)
	at /home/REDACTED/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:77896
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	```

**Comment by Zerebokep** [comment]
Same, Mac OS Ventura 13.4 (ARM), stopped working after updating vscode to 1.79.2.

**Comment by ks982579** [comment]
> I get the same error on my WIN 11 and the following solution not works.
> 
> `quickfix: at .vscode/settings.json add "prettier.prettierPath": "./node_modules/prettier" on settings { }`
> 
> Another MAC computer with same version works good, both version are 1.79.2

I was experiencing the same issue on WSL and can confirm that mclxly's solution worked for me.

**Comment by GabrielAnca** [comment]
Same issue on Windows 11 with **Remote: SSHSetting the prettier path fixed it.

**Comment by ntotten** [comment]
Duplicate of https://github.com/prettier/prettier-vscode/issues/3020
