### ISSUE TITLE
Prettier has an error when format with new version v9.15.0

### ISSUE THREAD

**Issue by acn-zhidong-sun** [prettier/prettier-vscode#3037]
**Prettier9.15.0**
As the title, errors occur when format code with prettier.
Because of the project security, i cant provide the code that needs to format.

ERROR:
```sh
["ERROR" - 12:21:18 PM] Error formatting document.

["ERROR" - 12:21:18 PM] parse(r,e,i={}){let a=wb(n,i);a.astFormat==="svelte-ast"&&(i.printer=qb["svelte-ast"]);let s=a.parse(r,e,i),l="...<omitted>...s} could not be cloned.

DataCloneError: parse(r,e,i={}){let a=wb(n,i);a.astFormat==="svelte-ast"&&(i.printer=qb["svelte-ast"]);let s=a.parse(r,e,i),l="...<omitted>...s} could not be cloned.

    at new DOMException (node:internal/per_context/domexception:72:5)

    at Worker.postMessage (node:internal/worker:343:5)

    at t.PrettierWorkerInstance.callMethod (d:\Users\a-meina.li\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17460)

    at t.PrettierWorkerInstance.format (d:\Users\a-meina.li\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17078)

    at t.default.format (d:\Users\a-meina.li\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:14808)

    at t.PrettierEditProvider.provideEdits (d:\Users\a-meina.li\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:11430)

    at U.provideDocumentFormattingEdits (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:45790)

["INFO" - 12:21:18 PM] Formatting completed in 30ms.
```

**Expected behavior:**
format normally

**Comment by fisker** [comment]
Transferred from prettier/prettier

**Comment by Chanzhaoyu** [comment]
Same

**Comment by JesseKoldewijn** [comment]
Same here, came in to work just to find out that nobody can currently format anything due to this update. 

Error output: 
```
["ERROR" - 9:26:44 AM] Error formatting document.
["ERROR" - 9:26:44 AM] parse(n,i,o={}){var v,S;let t=uI(e,o);t.astFormat==="svelte-ast"&&(o.printer=PI["svelte-ast"]);let u=t.parse(n,...<omitted>...u} could not be cloned.
DataCloneError: parse(n,i,o={}){var v,S;let t=uI(e,o);t.astFormat==="svelte-ast"&&(o.printer=PI["svelte-ast"]);let u=t.parse(n,...<omitted>...u} could not be cloned.
    at new DOMException (node:internal/per_context/domexception:72:5)
    at Worker.postMessage (node:internal/worker:343:5)
    at t.PrettierWorkerInstance.callMethod (c:\Users\jesse.koldewijn\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17460)
    at t.PrettierWorkerInstance.format (c:\Users\jesse.koldewijn\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:17078)
    at t.default.format (c:\Users\jesse.koldewijn\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:14808)
    at t.PrettierEditProvider.provideEdits (c:\Users\jesse.koldewijn\.vscode\extensions\esbenp.prettier-vscode-9.15.0\dist\extension.js:1:11430)
    at U.provideDocumentFormattingEdits (c:\Users\jesse.koldewijn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:101:45790)
```

Codebase details:
Next.js - 14.4.6
Tailwind plugins: Tailwindcss

**Comment by karaaa006** [comment]
Have a same problem

**Comment by JesseKoldewijn** [comment]
Also a duplicate of #3036

**Comment by Chanzhaoyu** [comment]
@JesseKoldewijn @karaaa006 @fisker 

rollback 9.14.0

<img width="1251" alt="image" src="https://github.com/prettier/prettier-vscode/assets/24789441/e71b2004-c212-43a8-b319-0f92d7a74ad0">

**Comment by fisker** [comment]
Close since duplicate of #3036
