### ISSUE TITLE
TypeError: A dynamic import callback was not specified. [can't format]

### ISSUE THREAD

**Issue by asportnoy** [prettier/prettier-vscode#3098]
### Summary
Just updated to v10.0.0 and got this error:
```
["INFO" - 10:00:09 AM] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:00:09 AM] Extension Version: 10.0.0.
["ERROR" - 10:00:09 AM] Error registering extension
["ERROR" - 10:00:09 AM] A dynamic import callback was not specified.
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:387:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at Object.<anonymous> (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/node_modules/prettier/index.cjs:600:23)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
    at Object.3920 (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:70593)
    at r (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:81444)
    at Object.604 (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:3243)
    at r (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:81444)
    at /Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:81611
    at /Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:82614
    at Object.<anonymous> (/Users/albert/.vscode/extensions/esbenp.prettier-vscode-10.0.0/dist/extension.js:1:82635)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
    at Module.load (node:internal/modules/cjs/loader:1058:32)
    at Module._load (node:internal/modules/cjs/loader:893:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28070)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:25404)
    at Function.u._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:91:22191)
    at Module.require (node:internal/modules/cjs/loader:1082:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:98)
    at i.rb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26583)
    at async Promise.all (index 0)
```

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Can't share

### Steps To Reproduce:

Just loaded the extension in v10.0.0

### Additional information

I see that this major version was just released 20 minutes ago so I'm assuming it's a bug that hasn't been discovered yet

**VS Code Version**:

1.80.2

**Prettier Extension Version**:

10.0.0 on macOS

## Prettier Log Output

Included above

**Comment by ntotten** [comment]
Duplicate of #3099
