### ISSUE TITLE
prettier 3.0 and prettier-vscode v10.1.0 won't load plugins

### ISSUE THREAD

**Issue by lewisflude** [prettier/prettier-vscode#3104]
### Summary

In my project, VS Code successfully loads my Prettier config, but when I try and format a `tsx` file it logs an error. Visual Studio Code is on version 1.80.2.

My config is as follows, and is exported as a package in a monorepo and used in the root of the monorepo (it seems to be loading successfully).

```/** @type {import("prettier").Options} */
export default {
  plugins: ["prettier-plugin-organize-imports", "prettier-plugin-tailwindcss"],
  tailwindFunctions: ["cva"],
  singleQuote: false,
};
```

### Steps To Reproduce:

1.  Use VS Code 1.80.2
1.  Set up a Turborepo project
1.  Make a package called `prettier-config` and export the config
1.  List packages `    "prettier": "^3.0.0",
`, `"prettier-plugin-organize-imports": "^3.2.3",` and `    "prettier-plugin-tailwindcss": "^0.4.1"
` as peerDependencies.
1.  Make sure the VS Code plugin is set up correctly
1.  Try formatting a React TSX file using Prettier from the command palette

### Expected result

The files should be formatted 

### Actual result

I get a pop up with the error.

> Command 'Format Document With...' resulted in an error
> Error resolve node module 'prettier-plugin-organize-imports'

I have tried multiple steps including removing plugins one at a time (same result for them all) as well as repositioning my prettier config and taking it out of the monorepo structure. I have tried require, import as well as pure text plugin definition based on the official docs as well as tried both esm and commonjs exports for the config.

I appreciate between Prettier and Prettier VS Code there are a fair few related issues, but on the off chance this bug report is useful I thought it would be worth posting.

### Additional information

package.json of the prettier-config package:

```{
  "name": "prettier-config",
  "version": "0.0.0",
  "main": "./index.js",
  "exports": {
    ".": "./index.js"
  },
  "type": "module",
  "engine": {
    "node": ">=16.0.0"
  },
  "peerDependencies": {
    "prettier": "^3.0.0",
    "prettier-plugin-organize-imports": "^3.2.3",
    "prettier-plugin-tailwindcss": "^0.4.1"
  }
}
```

**VS Code Version**:

Version: 1.80.2 (Universal)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T21:05:41.366Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 23.0.0

**Prettier Extension Version**: v10.1.0

**OS and version**: macOS 14.0 Beta (23A5276g)

## Prettier Log Output

```["INFO" - 18:34:42] Using config file at '/Users/lewisflude/Code/redacted/package.json'
["ERROR" - 18:34:42] Error handling text editor change
["ERROR" - 18:34:42] Error resolve node module 'prettier-plugin-organize-imports'
Error: Error resolve node module 'prettier-plugin-organize-imports'
    at n (/Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:2718)
    at /Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:3068
    at Array.map (<anonymous>)
    at t.resolveConfigPlugins (/Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:3003)
    at t.ModuleResolver.resolveConfig (/Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:7290)
    at t.default.getSelectors (/Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:11562)
    at t.default.handleActiveTextEditorChanged (/Users/lewisflude/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10924)
["INFO" - 18:34:44] Formatting file:///Users/lewisflude/Code/redacted/packages/ui/src/components/DataGrid/DataGrid.tsx
["INFO" - 18:34:44] Using config file at '/Users/lewisflude/Code/redacted/package.json'```

**Comment by nadbad** [comment]
I have also been having this issue for the past few days on linux. You can easily solve this issue by downgrading to v9.19.0!

**Comment by mike-hosseini** [comment]
Same issue here, I even added it to `settings.json` in VSCode but it is being ignored.

<img width="852" alt="image" src="https://github.com/prettier/prettier-vscode/assets/8545144/b95c36ec-fd2f-4598-a7be-7f88add06069">

**Comment by virtuallyunknown** [comment]
Please allow `prettier.plugins` as a vscode setting. I am not really a fan of having ton of static configuration files across all of my projects, and for that reason I keep all my prettier settings in the global vscode user `settings.json`.

But the problem is now that whenever you want to use a plugin, you have to:

1. Create a prettier configuration file in project root where you define your `plugins`.
2. Copy/paste your vscode settings into this configuration file.

I was using `prettier-plugin-tailwindcss` for ages without any issues whatsoever, but because of this now it no longer works.

**Comment by arx-8** [comment]
I was encountering the same problem, but now I can get `formatOnSave` to work perfectly with the following combination.

- vscode: 1.82.0
- esbenp.prettier-vscode: v10.1.0
- npm: 9.6.7
- node: v18.17.0
- prettier: 3.0.3
- prettier-plugin-organize-imports: 3.2.3

In my case, the cause was "prettier.prettierPath" in "settings.json".

>  "prettier.prettierPath": "./node_modules/prettier",

I had written the above value, but when I removed it, `formatOnSave` now works. I hope this will help.

---

The following comment may also be helpful:
https://github.com/prettier/prettier-vscode/issues/3007#issuecomment-1628836459

**Comment by frederikhors** [comment]
Nope

**Comment by vincerubinetti** [comment]
Wasted several hours of my life thinking I was doing something wrong. Turns out Prettier just hasn't worked for a pretty significant length of time.

Related: #3071 #3224 #3142

FYI, I think problems like this coming from the official, first-party extension is likely the reason for this rating:

<img width="170" alt="Screenshot 2023-12-18 at 1 21 00 PM" src="https://github.com/prettier/prettier-vscode/assets/8326331/b12e27ee-898d-4654-9ac8-081c53b79942">

**Comment by leonardsimonse** [comment]
What worked for me with:
- Prettier 3.1.1 
- Prettier VSCode 10.1.0
- prettier-plugin-svelte
- prettier-plugin-organize-imports
- prettier-plugin-tailwindcss

config:

```
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": [
		"prettier-plugin-svelte",
		"prettier-plugin-organize-imports",
		"prettier-plugin-tailwindcss"
	]
}
```
was setting:

```
"prettier.requireConfig": true
"prettier.configPath": "./.prettierrc"
```
only then the plugins started getting resolved

**Comment by lts20050703** [comment]
Can confirm that setting `"prettier.configPath": "./.prettierrc"` works. I don't think `"prettier.requireConfig": true` is necessary, though.

**Comment by CartoonFan** [comment]
Please keep open :+1:

**Comment by SLanberg** [comment]
Unusable. Issue still happening.

**Comment by nielsbom** [comment]
Issue still occurring.

**Comment by lts20050703** [comment]
@SLanberg @nielsbom Have you tried setting `"prettier.configPath": "./.prettierrc"` in `.vscode/settings.json`? (Or you can open settings, search for `prettier.configPath`, and set it to `./.prettierrc`)

**Comment by nielsbom** [comment]
> @SLanberg @nielsbom Have you tried setting `"prettier.configPath": "./.prettierrc"` in `.vscode/settings.json`? (Or you can open settings, search for `prettier.configPath`, and set it to `./.prettierrc`)

No. Is that useful without an actual `.prettierrc` file? (I'm fine with all the defaults)

**Comment by lts20050703** [comment]
Oh you don't have a `.prettierrc` file? Maybe try this?

> As shown in the [prettier-vscode docs](https://github.com/prettier/prettier-vscode?tab=readme-ov-file#prettierdocumentselectors), you can use the `prettier.documentSelectors` to target a specific file extension. The issue I had was with a `.sql` file, but you can also have the same setting for the `.tsx` file issues you are having
> 
> Example: Adding the settings below to the `.vscode/settings.json` will enable formatting for your `.sql` files
> 
> ```shell
> "prettier.documentSelectors": ["**/*.sql"],
> ```
> 
> I think I prefer this way instead of changing the `prettier configPath` as mentioned here [#3104 (comment)](https://github.com/prettier/prettier-vscode/issues/3104#issuecomment-1879606539)

**Comment by negroamarante** [comment]
Hi! I don't know if the issue I'm having is regarding plugins or what but on an Apex class I have this line **private static List<City__c> cities = [SELECT Id, Name FROM City__c] ?? new List<City__c>();** and when the prettier runs is giving this error:
`"ERROR" - 9:02:17 AM] Error formatting document.
["ERROR" - 9:02:17 AM] Unexpected token '?'..
Expecting ':' but was: ';'.
Error: Unexpected token '?'..
Expecting ':' but was: ';'.`
This is what I've got on my package.json:
![Screenshot 2024-06-25 at 9 04 35 AM](https://github.com/prettier/prettier-vscode/assets/56370227/051579c1-1b98-4133-aa02-918d484c990a)

I've been reading and trying some things but nothing works.. If I've remove the null-coalescing operator it works...

**Comment by Tanimodori** [comment]
With `"prettier.configPath": "./.prettierrc"` and `"prettier.requireConfig": true`, this expansion still produce the same error as above. 

Environments:

``` 
Prettier 3.3.3
Prettier VSCode 11.0.0
```

**Comment by tkrotoff** [comment]
For those having issues when specifying plugins using a string (`plugins: ['a-prettier-plugin']`), it can fail if you open multiple projects in the same VSCode window.
In this case vscode-eslint doesn't know from which node_modules to load the plugin (there is no root node_modules folder).

To fix this, explicitly import the plugin, either with `plugins: [require.resolve('a-prettier-plugin')]` (instead of `plugins: ['a-prettier-plugin']`) in CJS or using regular `import` in ESM (preferred, more future-proof):

```TypeScript
// File prettier.config.mjs

import prettierPlugin from 'a-prettier-plugin';

/** @type {import('prettier').Options} */
const config = {
  plugins: [prettierPlugin]
};

export default config;
```

**Comment by YtCsj** [comment]
need support vscode prettier set prettier plugins

**Comment by CartoonFan** [comment]
Not stale

**Comment by jgrafman** [comment]
Just want to point out that this is an issue for me on prettier v3.3.3 and prettier-vscode v11.0.0. I have to include the path to my config file in the workspace settings using `prettier.configPath` in order to use plugins. Not a satisfactory experience.

**Comment by tkrotoff** [comment]
Keep open

**Comment by Jme797** [comment]
https://marketplace.visualstudio.com/items?itemName=Jme797.prettier-vscode-extension

**Comment by vincerubinetti** [comment]
I opened a discussion about this a while ago that no one replied to: https://github.com/prettier/prettier-vscode/discussions/3234

I just want to be able to quickly format frequent one-off files (that don't have `node_modules`) with plugins like `prettier-plugin-css-order` from the extension

I have tried every work around in this thread and everything else I can think of. Nothing works. Unhelpful debug error messages about not being able to resolve modules/files that are clearly there.

At this point I would take the dirtiest workaround imaginable. Create a new dedicated global folder with prettier and all my plugins installed there? Use a different extension completely? Move into a cabin in the woods?

**Comment by hichemfantar** [comment]
i keep getting the invalid config in my [monorepo](https://github.com/shuding/nextra), it works when i remove the plugins

**Comment by jinwoo0103** [comment]
For those who have recently upgraded pnpm from v9 to v10 and are still encountering this issue,
try adding the following two lines to end of your `.npmrc` file.

```
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
```

then `pnpm install`

> For those who wants detail
> 1. `['*eslint*', '*prettier*']` was default option of `public-hoist-pattern` in pnpm v9 ([Link](https://pnpm.io/9.x/npmrc#public-hoist-pattern))
> 2. But It was removed in v10. ([Link](https://github.com/pnpm/pnpm/issues/8378))
> 3. So, you have to put it manually ([Link](https://github.com/pnpm/pnpm/issues/8378#issuecomment-2636152421))

**Comment by lachlancresswell** [comment]
My frontend was in `./frontend` along with `.prettierrc` and the config was found by default but the plugins were not loading (check `Extension Host` in the `Output` tab in Code).  I had a `node_modules` folder in my monorepo top level with prettier installed there. Removing this solved the issue.

**Comment by phawxby** [comment]
> For those having issues when specifying plugins using a string (`plugins: ['a-prettier-plugin']`), it can fail if you open multiple projects in the same VSCode window. In this case vscode-eslint doesn't know from which node_modules to load the plugin (there is no root node_modules folder).
> 
> To fix this, explicitly import the plugin with `plugins: [require.resolve('a-prettier-plugin')]` (instead of `plugins: ['a-prettier-plugin']`) in CJS (using regular `import` in ESM does not work with esbenp.prettier-vscode: "Invalid prettier configuration file detected"):
> 
> // File prettier.config.cjs
> 
> /** @type {import('prettier').Options} */
> module.exports = {
>   plugins: [require.resolve('a-prettier-plugin')]
> };
> See also [#3066 (comment)](https://github.com/prettier/prettier-vscode/issues/3066#issuecomment-2326581544)

This solution from @tkrotoff worked for me. I have a monorepo with the config and dependencies defined in a package so it can be imported into other disconnected repos and the plugin resolution was breaking. This sorted it out.

**Comment by karlhorky** [comment]
> in CJS (using regular `import` in ESM does not work with esbenp.prettier-vscode: "Invalid prettier configuration file detected"

@tkrotoff @phawxby `esbenp.prettier-vscode` with [Prettier 3.0](https://prettier.io/blog/2023/07/05/3.0.0.html) has ESM support. CommonJS config files (`prettier.config.cjs`) are not required with `esbenp.prettier-vscode`.

To use Prettier 3.0 with `esbenp.prettier-vscode`, install `prettier` in your project's `devDependencies` (`npm add --save-dev prettier` or similar) - as recommended by @ntotten here: 

- https://github.com/prettier/prettier-vscode/issues/3298#issuecomment-2289077132

Examples:

- `prettier.config.js` with `"type": "module"` in `package.json`
  - https://github.com/upleveled/preflight/blob/fe99e94d4664e550411dbe79b740b11ad70b746a/prettier.config.js
  - https://github.com/upleveled/eslint-config-upleveled/blob/bf19a1bd663776f74b0f381a7613dd0ad79c3ed7/prettier.config.js
  - https://github.com/upleveled/next-js-example-winter-2025-eu/blob/60cfa841b85be347045cfe53fe61db9f2133102d/prettier.config.js
- `prettier.config.mjs` with `"type": "commonjs"` in `package.json` (or no `"type"`, since `"type": "commonjs"` is default)
  - https://github.com/karlhorky/repro-prettier-config-mjs-with-type-commonjs/blob/main/prettier.config.mjs

**Comment by rublev** [comment]
Cant get this working with /bin/zsh + pnpm to save my fucking life:

```
["ERROR" - 9:13:04 PM] Error handling text editor change
["ERROR" - 9:13:04 PM] Command failed: pnpm root -g
/bin/sh: pnpm: command not found

Error: Command failed: pnpm root -g
/bin/sh: pnpm: command not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at checkExecSyncError (node:child_process:906:11)
	at execSync (node:child_process:978:15)
	at node:electron/js2c/node_init:2:16318
	at Object.get (/Users/rublev/.cursor/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:3572)
	at /Users/rublev/.cursor/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:5079
	at t.ModuleResolver.getPrettierInstance (/Users/rublev/.cursor/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:5094)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.default.handleActiveTextEditorChanged (/Users/rublev/.cursor/extensions/esbenp.prettier-vscode-11.0.0/dist/extension.js:1:10933)

```

I do not want to install it within my project. I just want to use the global extension defaults, thats it. Losing my fucking mind.

**Comment by ntotten** [comment]
This issue should be resolved in version 12 of the extension. Version 12 is currently in preview and is published only to the new Prettier organization. You can find that version here: https://marketplace.visualstudio.com/items?itemName=Prettier.prettier-vscode

Once we decide version 12 is stable it will be published to the old extension location as well.

Please test this issue in version 12 and let me know if this is still an issue. If we don't hear back this issue may be closed.
