### ISSUE TITLE
FormatOnSave hangs for an extended period

### ISSUE THREAD

**Issue by andrew-breunig** [prettier/prettier-vscode#3107]
Type: <b>Bug</b>

Our team stores GitHub CODEOWNERS configuration in our app repository at the path `./.github/CODEOWNERS`.

I and many colleagues use VSCode with the Prettier extension to format this configuration file on save.

When I make a change to this file and and attempt to save it, the save takes a very long time. I've observed that VSCode's "Code Helper (Plugin)" process consumes upwards of 99% of CPU capacity on my system while the operation is underway. VSCode's extension bisect utitility has identified the Prettier extension as the source of the issue.

https://code.visualstudio.com/blogs/2021/02/16/extension-bisect

Extension version: 10.1.0
VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 8adef7ce-57f8-48e5-b3aa-1d42b09f5a54|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by DerPipo** [comment]
I've got the same problem on macOS. After a restart the prettier output shows the following error log:

```
["INFO" - 13:09:02] Formatting file:///Users/user/projects/abc/webapp/src/pages/Component.tsx
["ERROR" - 13:09:02] Error resolving prettier configuration for /Users/user/projects/abc/webapp/src/pages/Component.tsx
["ERROR" - 13:09:02] A dynamic import callback was not specified.
TypeError: A dynamic import callback was not specified.
	at new NodeError (node:internal/errors:387:5)
	at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
	at Object.<anonymous> (/Users/user/projects/abc/webapp/.yarn/cache/prettier-npm-3.0.1-d00deab00c-e1f3f16c7f.zip/node_modules/prettier/index.cjs:600:23)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at require$$0.Module._extensions..js (/Users/user/projects/abc/webapp/.pnp.cjs:14389:33)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28084)
	at f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:25418)
	at C._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:19511)
	at require$$0.Module._load (/Users/user/projects/abc/webapp/.pnp.cjs:14234:31)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/Users/user/projects/abc/webapp/.yarn/sdks/prettier/index.js:20:18)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28084)
	at f._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:25418)
	at C._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at t.loadNodeModule (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:2829)
	at t.PrettierMainThreadInstance.import (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:17760)
	at t.ModuleResolver.getPrettierInstance (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:5728)
	at t.default.handleActiveTextEditorChanged (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10771)
	at t.default.handleActiveTextEditorChangedSync (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10373)
	at t.default.registerDisposables (/Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:13531)
	at /Users/user/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:82528
```

Downgrading to v9 via VS Code helps and works with prettier v3 for me.
