### ISSUE TITLE
Installed Prettier extension does not format and gives following error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by ldco2016** [prettier/prettier-vscode#3376]
<!--
SEE THIS GUIDE ON OPENING A GOOD ISSUE: https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue

**You must complete all steps in this checklist or the issue will be automatically closed.**

- [ ] Today, my prettier stopped working in the afternoon. It gave the following error:
- [ ] 
Error: Cannot find module 'prettier' from

- [ ] You can attempt to reproduce it with this repo: https://github.com/ldco2016/cars
- [ ] The expected result was that when I save javascript work in react, it auto formats.
- [ ] It did nothing.
- [ ] The machine is a MacOS Ventura

```
"ERROR" - 7:33:15 PM] Cannot find module 'prettier' from '/Users/danielcortes/Projects'
Error: Cannot find module 'prettier' from '/Users/danielcortes/Projects'
	at e.exports [as sync] (/Users/danielcortes/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:41190)
	at t.ModuleResolver.findPkg (/Users/danielcortes/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:8482)
	at t.ModuleResolver.getPrettierInstance (/Users/danielcortes/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:4633)
	at t.default.handleActiveTextEditorChanged (/Users/danielcortes/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:10967)
	at handleActiveTextEditorChangedSync (/Users/danielcortes/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:10569)
	at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:20765)
	at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
	at s.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:729)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:945)
	at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:29607)
	at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
	at n.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:28498)
	at n.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:26880)
	at u.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5502)
	at u.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:5268)
	at u.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:4361)
	at u.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:3440)
	at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:149:2227)
	at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
	at o.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:8018)
	at s.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:659)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:82:876)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:14173)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:6298)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
```

**Comment by ssbarnea** [comment]
That is clearly a bug report of very questionable quality, but I have to say that is real. I often get an error about not having prettier installed.

```
["INFO" - 14:26:54] Attempted to determine module path from /Users/ssbarnea/c/a/ansible-compat
["ERROR" - 14:26:54] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 14:26:54] Cannot find module 'prettier' from '/Users/ssbarnea/c/a/ansible-compat'
Error: Cannot find module 'prettier' from '/Users/ssbarnea/c/a/ansible-compat'
	at e.exports [as sync] (/Users/ssbarnea/.vscode/extensions/esbenp.prettier-vscode-1
```

I use multi-root workspaces, that is for sure and only some of these projects have a `package.json` in them with prettier, the others do not. Still, I do have prettier installed globally via `npm install -g prettier`, so I see no reason why the prettier vscode extension would fail to find a prettier.

I do suspect that this might be a newer regression, no more than 1-2 months old as I do not remember seeing it before.


```
$ which -a prettier
/Users/ssbarnea/.asdf/shims/prettier
/opt/homebrew/bin/prettier

ssbarnea@m1: ~/c/a/molecule chore/contraints
$ prettier --version
3.2.5
```

**Comment by Sding000** [comment]
I ran into the same problem.

**Comment by AsimAziz** [comment]
Ran into same issue
