### ISSUE TITLE
I need to completely uninstall prettier an reinstall it.

### ISSUE THREAD

**Issue by Tochiskool** [prettier/prettier-vscode#3383]
My prettier does not save on format. I dont have the knowledge to check the paths and do all those tricky stuffs. I have followed all kinds of videos base on the errors on youtube. Read documenttions uninstalled it completely then. That word prettier does not disappear beneath the vscode ui. 
First it said config now I donìt get it

at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (/private/var/folders/hz/_5x74xj57qv4wm2ncn3_2r4c0000gn/T/AppTranslocation/895C54F1-F8F8-4C4E-A1A9-521129BD0274/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:171:5632)
	at n._load (/private/var/folders/hz/_5x74xj57qv4wm2ncn3_2r4c0000gn/T/AppTranslocation/895C54F1-F8F8-4C4E-A1A9-521129BD0274/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:168:29551)
	at t._load (/private/var/folders/hz/_5x74xj57qv4wm2ncn3_2r4c0000gn/T/AppTranslocation/895C54F1-F8F8-4C4E-A1A9-521129BD0274/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (/private/var/folders/hz/_5x74xj57qv4wm2ncn3_2r4c0000gn/T/AppTranslocation/895C54F1-F8F8-4C4E-A1A9-521129BD0274/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:647)
	at t.loadNodeModule (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:2829)
	at t.PrettierMainThreadInstance.import (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:17964)
	at t.PrettierMainThreadInstance.resolveConfigFile (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:18661)
	at t.ModuleResolver.resolveConfig (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:6856)
	at t.ModuleResolver.getResolvedConfig (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:7735)
	at async t.default.format (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:14767)
	at async t.PrettierEditProvider.provideEdits (/Users/tochiskool/.vscode/extensions/esbenp.prettier-vscode-10.4.0/dist/extension.js:1:12876)
 

### Summary

_Short summary of what is going on or to provide context_.

### Github Repository to Reproduce Issue

Link to a Github repo that can be used to reproduce the issue.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**Prettier Extension Version**:

**OS and version**:

## Prettier Log Output

```
LOG GOES HERE. DO NOT USE A SCREENSHOT, COPY AND PASTE THE TEXT
```

**Comment by md-durjoy** [comment]
**### To fix the issue with Prettier not saving formatting in Visual Studio Code, you can try the following steps:**

    Verify Configuration: Check for a valid Prettier configuration file in your project. Create one if missing.

    Update Extension: Check for updates for the Prettier extension in Visual Studio Code's Extensions view and update if available.

    Reinstall Extension: If updating doesn't work, uninstall and reinstall the Prettier extension.

    Check Settings: Review Prettier extension settings in Visual Studio Code to ensure they match your preferences.

    Review Errors: Pay attention to any error messages related to Prettier formatting.

    Restart VS Code: Try restarting Visual Studio Code after making changes.

    Consult Documentation: Refer to Prettier's documentation for further troubleshooting.
