### ISSUE TITLE
Invalid Version

### ISSUE THREAD

**Issue by busyhe** [prettier/prettier-vscode#3436]
["ERROR" - 1:52:51 PM] Error handling text editor change
["ERROR" - 1:52:51 PM] Invalid Version: [object Object]
TypeError: Invalid Version: [object Object]
	at new SemVer (d:\workspace\project\**\node_modules\prettier\index.js:2461:13)
	at compare (d:\workspace\project\**\node_modules\prettier\index.js:2818:12)
	at Function.gte (d:\workspace\project\**\node_modules\prettier\index.js:2884:12)
	at filterSince (d:\workspace\project\**\node_modules\prettier\index.js:4321:82)
	at Array.filter (<anonymous>)
	at getSupportInfo (d:\workspace\project\**\node_modules\prettier\index.js:4254:6)
	at Object.getSupportInfo (d:\workspace\project\**\node_modules\prettier\index.js:44207:15)
	at t.PrettierMainThreadInstance.getSupportInfo (c:\Users\he.guo\.vscode\extensions\esbenp.prettier-vscode-10.4.0\dist\extension.js:1:18449)
	at t.default.getSelectors (c:\Users\he.guo\.vscode\extensions\esbenp.prettier-vscode-10.4.0\dist\extension.js:1:12023)
	at t.default.handleActiveTextEditorChanged (c:\Users\he.guo\.vscode\extensions\esbenp.prettier-vscode-10.4.0\dist\extension.js:1:11131)

**Comment by busyhe** [comment]
install vscode eslint 2.4.4 version. don't update 3.0.8
