### ISSUE TITLE
package.json with comments inside crashes

### ISSUE THREAD

**Issue by telemmaite** [prettier/prettier-vscode#429]
An auto generated `package.json` file with comments inside (I know right) crashes the extension.
Part of the error stack looks like 
`ERR Unexpected token '/' at 2:5 in ..\..\Users\xxx\Desktop\app\package.json
/**
^: JSONError: Unexpected token '/' at 2:5 in ..\..\Users\xxx\Desktop\app\package.json
/**
at module.exports (C:\Users\xxx\.vscode\extensions\esbenp.prettier-vscode-1.3.1\node_modules\parse-json\index.js:27:17)
at parse (C:\Users\xxx\.vscode\extensions\esbenp.prettier-vscode-1.3.1\node_modules\load-json-file\index.js:8:29)
at Function.module.exports.sync.fp [as sync] (C:\Users\xxx\.vscode\extensions\esbenp.prettier-vscode-1.3.1\node_modules\load-json-file\index.js:11:29)
at Function.module.exports.sync (C:\Users\xxx\.vscode\extensions\esbenp.prettier-vscode-1.3.1\node_modules\read-pkg\index.js:40:25)`

I had similar issue with vscode-eslint and creating `.eslintignore` file worked nicely
However creating `.prettierignore` with `package.json` does not work for `prettier-vscode`.

**Comment by CiGit** [comment]
We read your package.json file for every _sub_ file this extension would format. We search a prettier dependency.

**Comment by ntotten** [comment]
Package.json files don't support comments.
