### ISSUE TITLE
TSServer (Intellisense) Errors after Formatting

### ISSUE THREAD

**Issue by hasezoey** [prettier/prettier-vscode#569]
the TSServer Errors after Formatting the Code
Ouput: 
```
[Info  - 4:09:42 AM] Started TSServer
// formatting here
[Error  - 4:10:05 AM] 'getOutliningSpans' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at visitArray (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21685:26)
    at visitNodes (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15138:24)
    at forEachChild (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15593:21)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21671:21)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15133:24)
    at forEachChild (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15586:21)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21671:21)
    at visitArray (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21703:25)
    at visitNodes (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15138:24)
    at forEachChild (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15555:24)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21671:21)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21675:29)
    at visitArray (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21703:25)
    at visitNodes (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15138:24)
    at forEachChild (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15368:24)
    at visitNode (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21671:21)
    at updateTokenPositionsAndMarkElements (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21652:13)
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21499:13)
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15652:47)
    at updateLanguageServiceSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111154:44)
    at SyntaxTreeCache.getCurrentSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111100:30)
    at Object.getOutliningSpans (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111722:46)
    at IOSession.Session.getOutliningSpans (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:118898:45)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:118082:61)
    at C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:88
    at IOSession.Session.executeWithRequestId (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119522:28)
    at IOSession.Session.executeCommand (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:33)
    at IOSession.Session.onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119551:35)
    at Interface.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:120805:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 4:10:05 AM] 'navtree' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21463:22)
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15652:47)
    at updateLanguageServiceSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111154:44)
    at SyntaxTreeCache.getCurrentSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111100:30)
    at Object.getNavigationTree (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111690:71)
    at IOSession.Session.getNavigationTree (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119231:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:118219:61)
    at C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:88
    at IOSession.Session.executeWithRequestId (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119522:28)
    at IOSession.Session.executeCommand (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:33)
    at IOSession.Session.onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119551:35)
    at Interface.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:120805:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
[Error  - 4:10:06 AM] 'navtree' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:21463:22)
    at Object.updateSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:15652:47)
    at updateLanguageServiceSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111154:44)
    at SyntaxTreeCache.getCurrentSourceFile (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111100:30)
    at Object.getNavigationTree (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:111690:71)
    at IOSession.Session.getNavigationTree (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119231:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:118219:61)
    at C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:88
    at IOSession.Session.executeWithRequestId (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119522:28)
    at IOSession.Session.executeCommand (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119531:33)
    at IOSession.Session.onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:119551:35)
    at Interface.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\typescript\lib\tsserver.js:120805:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
and then after restarting the tsserver it works normal

Windows 10 (Pro) (Insider Builds)
VSCode User 1.26.1
Prettier (VSCode) 1.6.1
(cant provide the code, because it is in an private Project)
ESLint 5.4.0

**Comment by CiGit** [comment]
If you can't provide the code, you would need to debug it. But I don't see why formatting would break the server ...

**Comment by hasezoey** [comment]
I dont know why, but it dosnt happen to me anymore
current stats:
Windows 10 (Pro) (Insider Builds) (10.0.17755 Build 17755)
VSCode User 1.27.1
Prettier (VSCode) 1.6.1
ESLint 5.4.0

**Comment by CiGit** [comment]
Let's say it was a bad day for your computer 🔥 
and close this

**Comment by Introvertuous** [comment]
@CiGit can we re-open this issue, considering this is one of the top search results on google, this now acts as a pretty crappy artifact.

**Comment by hasezoey** [comment]
problem is, i cant reproduce it anymore ... (and i cant reopen it)

**Comment by Introvertuous** [comment]
@hasezoey that is why I @'d the other guy.

**Comment by hasezoey** [comment]
it was just for you (and everyone passing by) to know, and sorry...

**Comment by Introvertuous** [comment]
no need to apologise, you did nothing wrong, my aggression is mostly at the "your computer is having a bad day, so lets close this" comment, which is incredibly useless for everyone.
