### ISSUE TITLE
prettier-vscode will break in new vscode version

### ISSUE THREAD

**Issue by merobal** [prettier/prettier-vscode#701]
I tried to install `prettier-vscode` in Insider build of vscode (to debug https://github.com/Microsoft/vscode/issues/67055) and I got this error:

>Activating extension 'esbenp.prettier-vscode' failed: Cannot find module 'resolve'.
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'resolve'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
	at Function.Module._load (internal/modules/cjs/loader.js:528:25)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\requirePkg.js:5:17)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\requirePkg.js:37:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\PrettierEditProvider.js:14:22)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\PrettierEditProvider.js:165:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at n (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:874)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\extension.js:4:32)
	at Object.<anonymous> (C:\Users\balin\.vscode-insiders\extensions\esbenp.prettier-vscode-1.7.3\out\src\extension.js:60:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:748:347)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:728:770)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:37)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:31:542)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:5
	at t._doActivateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:738:113)
	at t._activateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:736:785)
	at Object.actualActivateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:733:633)
	at e._activateExtension (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:557)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:180
	at Array.map (<anonymous>)
	at e._activateExtensions (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:155)
	at e.activateByEvent (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:329:14)
	at t._activateByEvent (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:735:174)
	at t._handleEagerExtensions (c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:739:590)
	at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:743:250
	at process._tickCallback (internal/process/next_tick.js:68:7) (at c:\Users\balin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:331:792)
```

**Comment by CiGit** [comment]
I've seen other issues with such problems. It wasn't specific to Insider.

The only solution which seemed to work was reinstalling the extension.
